### ISSUE TITLE
Lua spam

### ISSUE THREAD

**Issue by cukiemunster** [BadBoy-Ultimate-Raider/BadBoy#100]
...rface\AddOns\BadBoy\System\engines\HealingEngine.lua:253: Usage: GetRaidRosterInfo(index)
Time: 01/15/15 22:19:26
Count: 1175
Stack: [C]: ?
[C]: in function `GetRaidRosterInfo'
...rface\AddOns\BadBoy\System\engines\HealingEngine.lua:253: in function `getUnitGroupNumber'
...rface\AddOns\BadBoy\System\engines\HealingEngine.lua:267: in function `UpdateUnit'
...rface\AddOns\BadBoy\System\engines\HealingEngine.lua:363: in function `Update'
Interface\AddOns\BadBoy\BadBoy.lua:295: in function `PulseUI'
Interface\AddOns\BadBoy\System\Core.lua:181: in function <Interface\AddOns\BadBoy\System\Core.lua:163>

Locals:

**Comment by cukiemunster** [comment]
This was persistent all night, had to turn off lua errors. Didn't matter what I did it wouldn't go away, reload wow, FH, /reload, nothing made it stop.

**Comment by CodeMyGit** [comment]
ill sort that out tomorrow morning if ingo didnt get to his computer tonight, thanks for feedback cukie sorry for the inconvenients

**Comment by ragnarger** [comment]
Sorry. Away Till sunday Night :( cant fix with mobile phone. 

Could cml Look ON it?

Sry drunken atm

**Comment by CodeMyGit** [comment]
i will sort this out

**Comment by CodeMyGit** [comment]
should be fixed
