### ISSUE TITLE
Won't dps with healing toggled off

### ISSUE THREAD

**Issue by cukiemunster** [BadBoy-Ultimate-Raider/BadBoy#101]
If you take the DoC talent and toggle off healing, it won't dps. Idk if it's because DoC is "technically" healing with Wrath.

**Comment by CodeMyGit** [comment]
you mean youd want to unselect healing toggle, enable dps toggle, select all with DoC and bot does nothing? I myself didnt intentionally write something to "dps heal", it should work normally, ill check this out thx for feedback dude

**Comment by cukiemunster** [comment]
Not exactly. For instance if I need to save mana and only want to heal with wrath Spam, and DoC healing is enough, disable healing and only dps as  long as the toggle is held for dps.

**Comment by CodeMyGit** [comment]
gotcha ill setup this

**Comment by CodeMyGit** [comment]
omg... that shit is great haha

**Comment by CodeMyGit** [comment]
should be fixed!

**Comment by cukiemunster** [comment]
Yeah, DoC is quickly becoming my favorite talent for that lvl, because it still provides decent healing and its almost free with the low mana cost. It allows you to save mana for more important healing. Although I am not sure if the dps toggle should toggle on/off on keypress like Rejuv All does now. Sometimes holding it down is a pain lol.

**Comment by CodeMyGit** [comment]
set key to none
