### ISSUE TITLE
castOffsneiveDispell modification

### ISSUE THREAD

**Issue by Mavmins** [BadBoy-Ultimate-Raider/BadBoy#102]
CML - new function is awesome, but could you upgrade it to be like Interrupts a little more if you have time?

So with new function it can remove enrage or magic from a list of dispells, but can we have, like interrupts a 'known' which would go from list and an 'all' which will dispell everything ?

Cheers

**Comment by CodeMyGit** [comment]
we cant really design the enrages to be on all. you should add all what you need to the list and please also remove the unwanted ones. I'm pretty sure there's junk in this lib as its a datamining of all available enrages.

I don't think i can add all/only known but i will sometime soon add all/target/mouse drop option

**Comment by Mavmins** [comment]
for enrages yep, agree, but for magic buffs on target we could remove all or raid specific ones ?

**Comment by CodeMyGit** [comment]
we could of course, but its risky. it would surely not be that usefull as it would try to remove a lot and might end up trying to dispel something forever... not sure how reliable IsSpellStealable arg is.
