### ISSUE TITLE
Addon error on DK Blood....

### ISSUE THREAD

**Issue by Chifo77** [BadBoy-Ultimate-Raider/BadBoy#103]
Hi...
When im using the DK blood rotation the addon is doing somthing that bring the addon error window to ignore or disaeble the addon, 

I re download the FH and the BadBoy addon and is doing the same thing....

Tks

**Comment by chumiiger** [comment]
Please enable "Show lua Errors" in WoW Settings (or get an Addon like Bugsack) and post the complete lua error, otherwise we won't be able to help you whats wrong

**Comment by cassrgs** [comment]
Hello there

I dont know if its the same error as on blood but after last update im getting the following error

95x ...\BadBoy\Rotations\Deathknight\Frost\Libs\Options.lua:121: bad argument #1 to 'tostring' (value expected)
[C]: in function `tostring'
...\BadBoy\Rotations\Deathknight\Frost\Libs\Options.lua:121: in function `FrostOptions'
BadBoy\Rotations\Deathknight\Frost\Frost.lua:5: in function `FrostDK'
BadBoy\System\Core.lua:236: in function <BadBoy\System\Core.lua:163>

Locals:
(*temporary) = <function> defined @BadBoy\Rotations\Deathknight\Frost\Libs\Options.lua:30

the addon dont even start
ty

**Comment by Chifo77** [comment]
HI
Sorry I was on a trip for work , ill download the addon and post the error ASAP..

ty

**Comment by Chifo77** [comment]
663x ...aceBadBoy\System\engines\InterruptsFrame.lua:366: attempt to call global 'UnitGUID' (a nil value)
...aceBadBoy\System\engines\InterruptsFrame.lua:366: in function `isSelectedTarget'
...aceBadBoy\System\engines\InterruptsFrame.lua:157: in function <...aceBadBoy\System\engines\InterruptsFrame.lua:134>
(tail call): ?
BadBoy\Rotations\Deathknight\Blood\Blood.lua:36: in function `Blood'
BadBoy\System\Core.lua:233: in function <BadBoy\System\Core.lua:163>

**Comment by Chifo77** [comment]
hi
It keps sending the error, the fist numbers are random 59x, 67x, 86x etc but the rest is the same, can someone helps me pls!!!!
It may be the setup i have on the addon, someone can tell me the best way to set up dhe Blood rotation or hace smthing like a guide or a readme...

TY


59x ...aceBadBoy\System\engines\InterruptsFrame.lua:366: attempt to call global 'UnitGUID' (a nil value)
 ...aceBadBoy\System\engines\InterruptsFrame.lua:366: in function  isSelectedTarget'
 ...aceBadBoy\System\engines\InterruptsFrame.lua:157: in function <...aceBadBoy\System\engines\InterruptsFrame.lua:134>
 (tail call): ?
 BadBoy\Rotations\Deathknight\Blood\Blood.lua:36: in function Blood'
 BadBoy\System\Core.lua:233: in function

**Comment by Chifo77** [comment]
Hi, 
I just delete cashe and WTF and it seams to work for the errors that i was having... i did LFR and work perfect!!!!

tks

**Comment by ragnarger** [comment]
you had the interrupter enabled. turn it off.
its corrupted atm.
