### ISSUE TITLE
Arms Warrior Low level

### ISSUE THREAD

**Issue by Kiwical** [BadBoy-Ultimate-Raider/BadBoy#104]
Wont work at low level dunno if its intended or not 

...erface\AddOns\BadBoy\Rotations\Warrior\Arms\Arms.lua:6: attempt to call global 'WarriorArmsConfig' (a nil value)
Time: 01/19/15 13:26:38
Count: 17499
Stack: [C]: in function `WarriorArmsConfig'
...erface\AddOns\BadBoy\Rotations\Warrior\Arms\Arms.lua:6: in function `ArmsWarrior'
Interface\AddOns\BadBoy\System\Core.lua:195: in function <Interface\AddOns\BadBoy\System\Core.lua:163>

**Comment by chumiiger** [comment]
definitely not intendet, but a /reload should fix it for now. it happens since I wrapped all arms specific stuff into a getSpecialization check to prefent interfering with functions / toggles etc from other profiles

**Comment by Kiwical** [comment]
ahh ok, well i tried it out and all it does is rend and execute when at 20% doesnt do mortal strike at all i have manually do it

**Comment by chumiiger** [comment]
oO
make sure you got the latest version, working fine for me right now.. if you are still having problems, try to remove your badboy folder and badboy.lua from wtf saved variables folder and delete your cache folder, then redownload badboy and try again

**Comment by Kiwical** [comment]
Yeah got the latest version i reinstalled badboy cleared cache removed lua, and nothing happens still.

I will charge at mob and it will cast rend and thats it the icon stays on rend until mob hits 20% then it will execute but nothing else no Mortal Strike just auto attack, im not sure what other options i need to have enabled, does badboy have a combat log

**Comment by chumiiger** [comment]
it has debug under general settings (left click on minimap icon).
i am sorry, but all i can say is that i used it last yesterday and had no problems..  are you sure you dont get any lua errors? do you have dynamic targetting on or off?

**Comment by Kiwical** [comment]
Dynamic targeting is off now i get this when i log in 

Message: ...erface\AddOns\BadBoy\Rotations\Warrior\Arms\Arms.lua:6: attempt to call global 'WarriorArmsConfig' (a nil value)
Time: 01/29/15 10:47:52
Count: 8007
Stack: [C]: in function `WarriorArmsConfig'
...erface\AddOns\BadBoy\Rotations\Warrior\Arms\Arms.lua:6: in function `ArmsWarrior'
Interface\AddOns\BadBoy\System\Core.lua:195: in function <Interface\AddOns\BadBoy\System\Core.lua:163>

**Comment by Kiwical** [comment]
[img]http://i.imgur.com/cOOlFIT.jpg[/img]

**Comment by Kiwical** [comment]
http://imgur.com/cOOlFIT

**Comment by chumiiger** [comment]
Well again.. That error is fixed by /reload. What i was asking for was if you get any errors when its stucks at rend and does only autoattack

**Comment by Kiwical** [comment]
No lua errors during combat
