### ISSUE TITLE
Need help with priest profile

### ISSUE THREAD

**Issue by afroduck** [BadBoy-Ultimate-Raider/BadBoy#105]
Id like a guide please on how to set this up for raiding and make it perform well. I dont know what options to leave on or off >.<

**Comment by afroduck** [comment]
Ive got it thorwing dots up and not casting anything at all lol

**Comment by afroduck** [comment]
Now its saying im too far away to do ANY abilities even near melee

**Comment by ragnarger** [comment]
yeah i'll write.

**Comment by ragnarger** [comment]
you want shadow?

**Comment by ragnarger** [comment]
added simple shadow how to
just try the options on the two dummies on your garrison ;)

**Comment by afroduck** [comment]
Not working in raids. It just stands there like a retard

**Comment by ragnarger** [comment]
answer my questions pls.
shadow or disc?

**Comment by afroduck** [comment]
Shadow.

**Comment by ragnarger** [comment]
shut down WoW.
delete the BadBoy.lua in the wtf folder.
update from git.
for me my rotation worked 2 hrs ago in raid

**Comment by afroduck** [comment]
Your ilvl and DPS its doing?

**Comment by ragnarger** [comment]
lvl 100.
ilvl more than 670
dps is enough

**Comment by afroduck** [comment]
How much dps does do?

**Comment by ragnarger** [comment]
tank n spank butcher mythic something over 30k

**Comment by afroduck** [comment]
I just did butcher heroic and did 17k

With 651 ilvl.. On other profile from HB I am doing 24k+

**Comment by ragnarger** [comment]
you read the pdf in priest folder i added?
dont know what you are doing wrong. for me and another user it goes well

**Comment by afroduck** [comment]
Do I need dynamic targetting on?

**Comment by ragnarger** [comment]
no. just take the target in target.

**Comment by afroduck** [comment]
http://i59.tinypic.com/f2r2hu.png

**Comment by afroduck** [comment]
above is image of my settings

**Comment by ragnarger** [comment]
turn off "dynamic targetting"
turn off "interrupts handler"
i dont use them really and they arent supported by me cause i never tested it.
rest should be okay

**Comment by afroduck** [comment]
It feels like its not casting enough is all :/

**Comment by afroduck** [comment]
I switch targets and it doesnt attack. throws some dots up then thats it.

**Comment by ragnarger** [comment]
i dont know what you want to tell me ^^
you have the most actual release? i had some bugs in there. just update it.

**Comment by afroduck** [comment]
Yes. I just did and deleted folders.

**Comment by ragnarger** [comment]
then i dont know any things.
go into garrison and test the rotation and its behaviours on the dummies.
sry :(

**Comment by ragnarger** [comment]
i think i have found a bug. deactivate the "MS Targets" option.
i will look and fix this...

**Comment by ragnarger** [comment]
should be fixed now
