### ISSUE TITLE
[Feral] Cleave/AoE question

### ISSUE THREAD

**Issue by Neretil** [BadBoy-Ultimate-Raider/BadBoy#107]
Hai!

I can't make this 2 options work correcty. Am i doing something wrong or that's how they work?

Cleave:
Dynamic target and/or Cleave rotation is turned on, but the bot just does it's normal singletarget rotation, doesn't switch target, doesn't keep bleeds up. Tested it on the Twins, Brackenspore and Tectus mythic, i have to watch the timers and manually switch target all the time. On balance spec it works perfectly, there is moonfire/sunfire on every single mob if it's enabled.

AoE:
So the best feral AoE is Rake everything, keep up Thrash and Swipe only if you have 10+ target.
If AoE or Automatic rotation is enabled the bot does it's single target rotation and use Swipe from time to time, seems random to me. No Rake spread by target switch, no Thrash use at all, it just use the most useless spell (swipe) in the game without Thrash (what could boost it at least)

**Comment by SBRDev3** [comment]
The idea was that Cleave controlled multi-dotting and AoE controlled using AoE specific rotation logic. Admittedly I probably could have done a better job of this but for the most part you would want to mutli-dot on any extra targets beyond the first but swipe/shred usage swap occurs at 3+ targets according to simc. I will see if i can figure a better solution rather than just swapping to single target mode for multi-dotting.

**Comment by CuteOne** [comment]
With the way feral is these days the Cleave toggle is more or less a Single/AoE toggle, i have just updated the logic to the latest sim files so hopefully this is no longer an issue.

**Comment by Neretil** [comment]
Thanks, i'll test the update tonight.
What about the Dynamic targeting?

**Comment by Neretil** [comment]
Tested it.
Thash is only applied when i have more than 50 energy (Tigers Fury), otherwise as soon as i have 45 energy a swipe is casted. Dynamic targeting doesn't work at all.

**Comment by CuteOne** [comment]
Do you have Dynamic Targetting enabled in the bot (not profile) options?

**Comment by cassrgs** [comment]
i guess a check on thrash and rake on targets in melee range to be able to cast swipe could be usefull?

**Comment by CuteOne** [comment]
I just did some testing and every test i did had different results, and im also getting reports with bad rake usage....looking at the code I don't see what is causing any of these issues. I guess just give me some time and maybe i can figure out wth is going on.

**Comment by Neretil** [comment]
Yes, Dynamic targeting is enabled in the bot since weeks. It never worked for me. For example the twins are standing yards from eachother but i never saw a Rake or Rip applied on the one im not targeting. 

Check out the balance profile to see what im missing. Turn on Dynamic Target in bot and Multi Moonfire in the profile, there will be Moonfire on every single mob im in combat with under seconds.

**Comment by Neretil** [comment]
Wrong button
