### ISSUE TITLE
Raise an Ally Blood DK

### ISSUE THREAD

**Issue by Chifo77** [BadBoy-Ultimate-Raider/BadBoy#108]
Hi all

I want to know if is a way to use raise an ally on the rotation, I need to stop the rotation and do it manualy, then start it again... 

TY

**Comment by guiguziking** [comment]
You want a Pause shortcut key? Like RightAltKey ?
May be you can put this in you lua.

        if poweruptime==nil then poweruptime=0 end
        if powerstoptime==nil then powerstoptime=0 end
        --RightAltKey Pause\Start
        if IsRightAltKeyDown() and BadBoy_data['Power'] == 1 and powerstoptime <= GetTime() - 0.3 then 
            ChatOverlay("|cffFF0000BadBoy Paused", 5); 
            BadBoy_data['Power'] = 0;
            poweruptime = GetTime();
            return;
        elseif IsRightAltKeyDown() and BadBoy_data['Power'] == 0 and poweruptime <= GetTime() - 0.3 then
            ChatOverlay("|cff33FF33BadBoy Start", 5); 
            BadBoy_data['Power'] = 1;
            powerstoptime = GetTime();
            return;
        end
