### ISSUE TITLE
Assassin rogue issues

### ISSUE THREAD

**Issue by Kiwical** [BadBoy-Ultimate-Raider/BadBoy#109]
Combat randomly stops either during or after fights specially in dungeons, i switched off dynamtic targeting and interrupt handler cause im not sure whats causing the issue this is the LUA error im getting, or is it the Auctionator addon i dunno.

essage: ...nterface\AddOns\BadBoy\ClassLibs\Rogue\Functions.lua:14: attempt to index field '?' (a nil value)
Time: 01/24/15 10:00:54
Count: 1
Stack: Interface\AddOns\Auctionator\AtrErrorInspector.lua:106: in function <Interface\AddOns\Auctionator\AtrErrorInspector.lua:51>
[C]: ?
...nterface\AddOns\BadBoy\ClassLibs\Rogue\Functions.lua:14: in function <...nterface\AddOns\BadBoy\ClassLibs\Rogue\Functions.lua:6>

Locals: msg = " ...nterface\AddOns\BadBoy\ClassLibs\Rogue\Functions.lua:14: attempt to index field '?' (a nil value)"
funcnames = <table> {
}
funcstr = ""
looksLikeAuctionatorError = false
inAtrErrorHandler = true
origErrorHandler = <function> defined Interface\FrameXML\BasicControls.xml:<Scripts>:4
zc = <table> {
 msg_anm = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:675
 msg = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:775
 GetArrayElemOrFirst = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:161
 NumToBool = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:600
 StringStartsWith = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:968
 TrimQuotes = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:1011
 padstring = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:191
 GetArrayElemOrNil = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:176
 BoolToNum = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:590
 periodic = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:366
 pluralizeIf = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:621
 msg_pink = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:647
 SetTextIf = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:47
 HSV2RGB = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:690
 LinkFromItemID = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:543
 IsBattlePetLink = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:432
 printableLink = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:1075
 PrintTable = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:396
 PrintKeysSorted = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:121
 Negate = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:610
 IsTextQuoted = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:992
 CopyDeep = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:1060
 UTF8_Truncate = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:139
 val2gsc = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:825
 words = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:295
 tableIsEmpty = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:384
 Max = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:95
 printstack = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:1099
 pluralize = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:632
 RawItemIDfromLink = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:460
 EnableDisable = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:25
 TrimBrackets = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:1031
 ParseBattlePetLink = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:440
 ShowHide = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:36
 QuoteString = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:999
 round = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:640
 StringEndsWith = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:948
 priceToMoneyString = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:879
 tallyPrint = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:1190
 msg_yellow = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:648
 If = <function> defined @Interface\AddOns\Auctionator\zcUtils.lua:110
 Min =

**Comment by Kiwical** [comment]
And this 

Message: ...ace\AddOns\BadBoy\System\engines\InterruptsFrame.lua:365: attempt to call global 'UnitGUID' (a nil value)
Time: 01/24/15 10:38:27
Count: 5131
Stack: [C]: in function `UnitGUID'
...ace\AddOns\BadBoy\System\engines\InterruptsFrame.lua:365: in function `isSelectedTarget'
...ace\AddOns\BadBoy\System\engines\InterruptsFrame.lua:157: in function <...ace\AddOns\BadBoy\System\engines\InterruptsFrame.lua:134>
(tail call): ?
...dBoy\Rotations\Rogue\Assassination\Assassination.lua:239: in function `AssassinationRogue'
Interface\AddOns\BadBoy\System\Core.lua:218: in function <Interface\AddOns\BadBoy\System\Core.lua:163>

Locals:

**Comment by Kiwical** [comment]
Ive switched off Interrupt Handler also have disabled it in my rotation, dynamtic targeting is enabled, ive had no LUA errors at all, profile seem to  be running ok

**Comment by ragnarger** [comment]
the interrupter seems to be not working correct at the moment. 
turn it off and all should run its way!

**Comment by CuteOne** [comment]
I need to find time to look over Assassination, dynamic targetting doesn't seem to be working (if i even implemented it on there yet) I just don't know when I will get to it.

**Comment by CuteOne** [comment]
I had re-enabled interrupts, please continue to not enable Interrupts Engine
