### ISSUE TITLE
Feral racial toggle

### ISSUE THREAD

**Issue by cassrgs** [BadBoy-Ultimate-Raider/BadBoy#110]
Hello there
Could we have a toggle for racials on feral profile? When im soloing stuff on my nelf it makes shadowmeld reset fights >.<

**Comment by CuteOne** [comment]
I can do 1 better and have it only work in non-solo environments.

**Comment by cassrgs** [comment]
A toggle could be a good option cause a instance only check could still
reset fights when soloing old raids and dungeons ;)
 Em 23/01/2015 23:37, "ph34rt3hcute1" <notifications@github.com> escreveu:

**Comment by cassrgs** [comment]
i just edited shadowmeld code and put "and UseProwl()" so its easier to turn it on and off with prowl button since the instance check still reset fights when soloing old content
