### ISSUE TITLE
Best class to pull top tier numbers?

### ISSUE THREAD

**Issue by popster** [BadBoy-Ultimate-Raider/BadBoy#111]
Hope I'm not misusing this forum, but since you guys are constantly working on this stuff I was wondering if you had an opinion on the best class that would get top ranks on warcraftlogs ect. with minimal effort?

I'm currently playing a DPS warrior and all the cooldown planning is a drag when I just want to turn on badboy and see my name at the top :3

**Comment by GabbzGit** [comment]
Well tbh its dependent on itemlevel and how OP the class is.
Being top DPS is easy tbh if you have the gear.
Pick a class and help the developer to improve the profile and you get rankings easy.
With our enemy engine a dot class will always shine cause we will always know if mobs have dots on them or not.
And Knowledge about the class helps

**Comment by chumiiger** [comment]
Regarding warrior.. i think both, arms and fury are "ok" as how they are right now. there are minor things to improve, but if you got some gear and choose the right spec for each boss, you can easily pull some good numbers. Just try it and tell me what you like / dont like and I will see what I can change

**Comment by Neretil** [comment]
The Feral profile is really good on single/double target fights. Im using it since 2 months and im one of the top dps in a 5/7 mythic guild. ( and ferals are the bottom on warcraftlogs)

Thanks CuteOne!

**Comment by popster** [comment]
All the profiles are really good, I've raided on most classes and most of the problems classes have are due to buggy TimeToDie(s) and hitboxes that don't count as an enemy unless you're in it (Bracken + Twins).
