### ISSUE TITLE
Help with the Interrupt's!!!

### ISSUE THREAD

**Issue by Chifo77** [BadBoy-Ultimate-Raider/BadBoy#116]
I dont know if whith the new updates we need to change smthing on the interrupt's... they are not working in the Blood dk and in the Unholly....

When i get home i'll post the error because i dont have the addon istaledi on my lap.....

 Tks for ur work... i love ur profiles ;)

**Comment by ragnarger** [comment]
interrupts are not working atm. 
we are working on the code, because it caused some #134 errors.

**Comment by Chifo77** [comment]
Ok Tks!!!!!

**Comment by Chifo77** [comment]
pls let me know!!!!

**Comment by Chifo77** [comment]
The interrupts are working just fine for me in DK (blood $ Unholly) and in Druid (Feral) profiles...\\TKS

**Comment by Chifo77** [comment]
ARE THE INTERRUPTS WORKING???

**Comment by CuteOne** [comment]
Feral, Frost DK, Assassination, and Windwalker Interrupts should be working again, please do not enable Interrupt Engine.
