### ISSUE TITLE
#getEnemies not working?

### ISSUE THREAD

**Issue by popster** [BadBoy-Ultimate-Raider/BadBoy#117]
Did a fresh update of BB this morning and auto AoE isn't workong on Combat rogue or Arms warrior

/dump #getEnemies("player",40)
returns 0 regardless of how many enemies i put myself around

/dump getEnemies("player",40)
returns empty table

**Comment by ragnarger** [comment]
i have no rogue but i have an arms warrior.
will look and test it this night.

**Comment by popster** [comment]
I was able to fix it by switching to #enemiesTable ... just some profiles out of date with new changes!

**Comment by popster** [comment]
#enemiesTable is working... is there anyway to limit the range?

**Comment by popster** [comment]
feral auto AoE also broken
#enemiesTable still dumps the # of enemies around, but is there method to limit the range?

**Comment by popster** [comment]
ok quick fix for any melee BBers who raid tonight, go to BadBoy.lua and change line 266 from max distance to 8, then change any profile that uses #getEnemies("player",8) to #enemiesTable

**Comment by ragnarger** [comment]
working on a fix atm

**Comment by ragnarger** [comment]
committed.
should be fixed now.
