### ISSUE TITLE
Crashing on reload

### ISSUE THREAD

**Issue by popster** [BadBoy-Ultimate-Raider/BadBoy#118]
Anybody else crashing if they reload BB while in a raid? Last night it would crash on nearly every reload, only while I was in a raid group though

This is only with newest version of BB, other crashing issues seem to be fixed with recent objectcall changes

**Comment by ragnarger** [comment]
were you infight while reloading?

**Comment by averykey** [comment]
get http://www.curse.com/addons/wow/addon-loader and help me test

**Comment by ragnarger** [comment]
with "delayed" the addon wont be loaded if you are infight and reload

**Comment by ragnarger** [comment]
maybe we can use: PLAYER_ALIVE
ressource: http://www.wowwiki.com/AddOn_loading_process

**Comment by averykey** [comment]
simple fix in addon loader, just search for combat in conditions and comment that stuff out. still works fine. havent had a crash yet
