### ISSUE TITLE
[Druid][Feral]Broken

### ISSUE THREAD

**Issue by Neretil** [BadBoy-Ultimate-Raider/BadBoy#119]
I updated the bot today and it went crazy. I didn't change any settings, worked perfectly last night.

Problems:
-Doesn't apply and refresh Rip and Rake
-Doesn't use Berserk at all (Incarnation works)

Reinstalled the old version from my trash bin and it works again

**Comment by ragnarger** [comment]
we fixed the #134 errors. now we have to fix several functions.
getEnemies was fixed last night.
getTimeToDie is not working atm... i will look on it the comin nights.
some other functions may be defect too...

**Comment by Neretil** [comment]
Thanks for the info

**Comment by Neretil** [comment]
It's working again. Thanks
