### ISSUE TITLE
Feral druid RAKE issue

### ISSUE THREAD

**Issue by popster** [BadBoy-Ultimate-Raider/BadBoy#121]
There is a problem with rake in that it sometimes gets stuck and badboy will spam rake even though rake is applied and there is no good reason to refresh it

For example It will cast rake 3 times on the same target within 4 seconds before moving on.

It seems to happen most (or maybe only happen) on AoE/cleave fights like maidens and twins, so something wrong with with the enemies table?

**Comment by popster** [comment]
Looking into simcraft and comparing the code, it looks like they've recently updated the rake conditions a lot compared to the ones currently in the feral profile

**Comment by CuteOne** [comment]
I built rotation based on active simcraft apl discussion here, http://fluiddruid.net/forum/viewtopic.php?f=3&t=5024&start=125#p27509

**Comment by popster** [comment]
Rotation definitely works -amazing- other than this, but something causing it to recast rake rapidly sometimes when using the enemies table
