### ISSUE TITLE
Ret pally tweaks #2

### ISSUE THREAD

**Issue by malloot** [BadBoy-Ultimate-Raider/BadBoy#122]
(request)

Would it be possible to update the Ret Rotation to the newest SimC version?
there are some changes to the aoe rotation (just 1-2 and 3+ now) and the seraphim uptime is better and it does the same in less code then the version we are on now. 

And the protection tools don't seem to be working: Lay on hands, Divine Protection and Hand of protection are not being cast. 
What also would be great is a option(toggle) to cast heals and shields somewhere low in the rotation so it would for example cast Flash of light with 3 stacks of selfless healer on a target with <25% health if the rotation has no holy power generators up and is under 5hp. Or rebuffs Sacred Shield on ourselves after Exorcism so the rotation is not to losing dps to much for it.

**Comment by malloot** [comment]
I also have massive fps issues with the ret profile, is this something badboy wide or only this profile? (have no other classes to test on, prot doesn't work at all)

fps goes from stable 60 with verical sync to about 18 in a raid with badboy with the ret profile. Firehack with PE works without fps drop.

**Comment by ragnarger** [comment]
Try to go in options in healing Engine and Change the update time once. 
Then look at fps again.

**Comment by malloot** [comment]
Tried setting it at 50 500 1000 1500 and 2000, the exact same fps drop on all those settings

**Comment by ragnarger** [comment]
then the problem is not brought by the healing engine i would say

**Comment by Defmaster** [comment]
I'm also using the ret profile for raiding. You should also check the option "Update speed" (?) which reduces the load. The option is next to the healing engine update setting.

I also updated the ret und prot profile for myself, dont know if you want them @ragnarger.
Also dont really know how to push the made updates to git, as i'm new to git.

Changes i made to ret profile:
- usage of scabbard of kyanos
- better Hammer of Wrath usage (its currently using the old spell id for HoW < 20%, but HoW has a own spell id for hp < 35%)
- updated T17 set bonus usage
- updated 16yard to 12yard (DS range w/ FV)
- maybe some other stuff i dont remember now

**Comment by ragnarger** [comment]
you can send a pull request. i'll look over it and accept it then. 
after this your updates are in the project.

**Comment by ragnarger** [comment]
pull request accepted!
