### ISSUE TITLE
#getEnemies("player",8) broken on certain encounters

### ISSUE THREAD

**Issue by popster** [BadBoy-Ultimate-Raider/BadBoy#123]
There's three fights where #getEnemies("player",8) doesn't work correctly, you actually have to be in THEIR HITBOX for it to register the target as a unit

There fights are
Highmaul:
Tectus
Brackenspore
Twins

BRF:
Franz and Hagz

Example: On bracken spore you have to literally be inside his hitbox for /dump #getEnemies("player",8) to show him as a target

Just wanted to point it out, it breaks AoE rotations

something to note is #enemiesTable works just fine, only problem is it's not a good idea for melee to use it since it's using max distance

**Comment by CuteOne** [comment]
i hadn't noticed a problem personally but it should be looked into none-the-less

**Comment by guiguziking** [comment]
Try this:
    function getEnemiesnumbers(unit,Radius,flag)
        local Units = 0
        for i = 1, #enemiesTable do
            if flag == "pve" or flag == nil then
                if getDistanceXYZ(unit,i) <= Radius then
                    Units = Units+1
                end
            elseif flag == "pvp" then
                if getDistanceXYZ(unit,i) <= Radius and UnitIsPlayer(enemiesTable[i].unit) then
                    Units = Units+1
                end
            end
        end
        return Units
    end

**Comment by Defmaster** [comment]
BRF:
Kromog

He also does not get recognized.
