### ISSUE TITLE
Feral issues (again)

### ISSUE THREAD

**Issue by Specified** [BadBoy-Ultimate-Raider/BadBoy#124]
Looks like feral is having the same issues as it did previously(not using rip, rake, or berserk; same issue posted over a week ago) since I updated it last night before raid(Feb 16th) and this morning(Feb 17th). 

Not sure what caused it to revert back. I believe the sync/revert from Gabbz was the last update I did before heading into BRF. Could this be the issue?

If I could get any insight, I'd really appreciate it folks. Thanks!

**Comment by Specified** [comment]
Tried out the profile on the garrison dummy, and rake is being used, but not rip or berserk.

**Comment by CuteOne** [comment]
I just pushed a change an hour ago that should fix it

**Comment by Specified** [comment]
Yeah, I updated when I posted. But I will try again to be sure.

**Comment by CuteOne** [comment]
I made another push with the actual files from my last feral commit

**Comment by Specified** [comment]
Updated again, still no rip or berserk while on the dummy. It's not game breaking, so I will try in BRF and see if anything else pops up.

**Comment by Specified** [comment]
Looks like the most recent update fixed everything! So far so good.

Thanks again CuteOne!

**Comment by CuteOne** [comment]
Found an issue where the AoE threshold (point where bot will use swipe over shred) was forcing the use of swipe but the cast logic on swipe was set for a higher threshold unless under incarnation, this resulted in no generators being used when facing exactly 3 enemies in an 8yrd range.

**Comment by CuteOne** [comment]
Yep was just commenting about it, closed.
