### ISSUE TITLE
Bug collection

### ISSUE THREAD

**Issue by Neretil** [BadBoy-Ultimate-Raider/BadBoy#126]
Im done leveling every class to lvl100 with this wonderful bot and here is a list about the bugs i found.
And a question: Is there any way to honor you guys? It feels so wrong to enjoy this awesome bot for free and see all that hard work spent on it without giving anything in return

Druid -Balance
-Incarnation is always used even with "no cooldowns" setting on mini bar and "CDs" setting in the profile menu.
-Celestial Alignement is never used even with "All Cooldowns" setting on minibar and "Always" setting in the profile menu. In raids it rarely it works, but i couldn't figure out a pattern why and when.
-If i have a healthstone in my bags the bot try to use it continuously

Hunter - Marksman
-Focusing Shot talent needs some tunging, it's often used even if most of the 50 focus is wasted (cast starts at 80+ focus)

Warlock - Demo
-The mini bar is broken, it shows retribution paladin skills.
-Bot doesn't use Soul Fire, Metamorphosis and other key elements from the rotation

Priest - Shadow
-The bot use Devouring Plague as an execute skill instead of SW:Death, it's allways wasted on mobs with really low hp.

Warrior - Fury
-Mini bar doesen't load after logging in, allways have to /reload to make it appear

Warrior - Protection
-The bot is broken. As soon as i switch spec to prot the bot cause insane lag, the minibar goes crazy and spell icons are flashing on it .

Paladin - Protection
-The bot is broken. Same as the warrior. Switching to prot talent cause insane lag and not playable.

**Comment by malloot** [comment]
2nd the broken prot profile, would be awsome if updated. Also WTB donation link for awesome work on this addon. Amazing community work

**Comment by CuteOne** [comment]
Who would you dontate to? There are several devs actively working on the
bot.

**Comment by ragnarger** [comment]
>Priest - Shadow
>-The bot use Devouring Plague as an execute skill instead of SW:Death, it's allways wasted on mobs >with really low hp.

The Shadow Profile is coded for lvl100. never tested anything below that. it also needs the lvl100 talents to work correctly

**Comment by malloot** [comment]
@CuteOne The dev beerfunds clearly!
Also just trying to be thankfull man, don't have to start punching holes in my logic directly...

**Comment by CuteOne** [comment]
sorry i am good at that =)
