### ISSUE TITLE
Enhancement Shaman-Spamming Searing Totem

### ISSUE THREAD

**Issue by bradstory** [BadBoy-Ultimate-Raider/BadBoy#127]
Hello! 
Using Cpoworks routine for Enhancement seems to only be spamming Searing Totem for me. 
Any ideas how to fix this?

**Comment by knightwish** [comment]
Reload works :)

**Comment by Defmaster** [comment]
Working on a current branch which fixes some minor problems/bugs within some profiles.
FireNova got fixed and ascendance to (used wrong SpellID)

Unfortunately "spamming searing totem" is a FireHack Bug. It's on his radar, as it already beeing reported: http://www.fh-wow.com/forums/showthread.php?7937-Firehack-Lua-Bug

Maybe the totemdistance function can be rewritten to avoid this bug.
For the time being reload until it works :D
