### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Neretil** [BadBoy-Ultimate-Raider/BadBoy#129]
Is this just me?

![eerrtt](https://cloud.githubusercontent.com/assets/10140030/6375786/ac4d1976-bd19-11e4-837a-75fb24ca51d5.png)

**Comment by CuteOne** [comment]
Re-download FireHack

**Comment by Neretil** [comment]
Hm. Thanks. I tought it download the latest updates or at least warn me when i log in.
