### ISSUE TITLE
windwalker monk

### ISSUE THREAD

**Issue by Moonst** [BadBoy-Ultimate-Raider/BadBoy#130]
might want to switch the logic for the auto aoe on ww to 4 or more targets for spinning crane kick i notice when there are three targets close it will spam spinning crane kick but ignore fists of fury
other than that solid rotation although i am going to re download because i was having massive frame rate spikes thanks cuteone for a great rotation

**Comment by ragnarger** [comment]
for frame rate issues try to change in healing engine tab "update timer" on time

**Comment by Moonst** [comment]
kk thnx ragnarger

**Comment by ragnarger** [comment]
Report us how and if it works. 
Just ragnar ;)

**Comment by Moonst** [comment]
it didnt work i tried useing the update speed i tried lowering it and nothing and tried increaseing it and nothing also i use on other toons and i use brewmaster and it doesnt inmpact the fps like the ww does although i can still say the brewmaster is still not attacking the hands on Kromog

**Comment by ragnarger** [comment]
Then the fps probs are from some code inside the rotation I would say

**Comment by Defmaster** [comment]
I also use the ww profile on an alt. As soon as the profile / badboy gets activated in raid (like lfr) fps goes down from 60fps to 20fps. 
I will take a deeper look into the code. I suspect it has something to do with the SEF code, but dont know for sure.

**Comment by ragnarger** [comment]
is this problem only on windwalker?

**Comment by Moonst** [comment]
yeah i don't have any prob really with any other profile i know cuteone is not really working on these any more, although i can say out side of raid its ok and pretty smooth

**Comment by Defmaster** [comment]
I just looked a bit on the code and it's a bit confusing :D 
A function GroupInfo() is called, but i dont know why its used, as a ww has no cooldown which could be used an raid member ? This is called every time in a raid and should consume some time to execute as it iterates through all raid members. 
Maybe i can spare some time today or tomorow to test something, to reduce execution time and thus fps drop.

**Comment by CuteOne** [comment]
I will try to look at this this weekend but I doubt i have wow or fh time.

**Comment by Defmaster** [comment]
I looked over it and tested in LFR. As i thought the fps drop is caused by the GroupInfo() function, which is also used by SEF to not use it on not yet pulled mobs. Also the rotation could get a little love.
Maybe i will do an overhaul if @CuteOne isnt playing anymore.

**Comment by Moonst** [comment]
yeah i dont use ww too much any more seeing as how they made me go brew master but when i solo i like to be able to use brew so all the love would be appreciated i wish i knew how to code =/ any how nice to see ya around cuteone and defmaster thnx for looking into it

**Comment by Defmaster** [comment]
As long as you are not in a group or raid the ww profile should not cause a fps drop. But as i sometimes run lfr with my monk alt i will probably update the rotation.

**Comment by Defmaster** [comment]
Just wanted to give an update.
I re-wrote nearly the entire windwalker profile. Rotation (SimC) is working and SEF also. I used some of @CuteOne code, like the SEF one and modified a little, so it use no excessive cpu time.
It's not final yet, as i have to implement options (toggle, cooldowns and so on).
But a short LFR test showed good results :)

Head some headache because of some own stupidity and blizzards tigereyebrew buff upfuck <.<

**Comment by CuteOne** [comment]
If you need any help I am still around, just not game/fh time.

**Comment by ragnarger** [comment]
defmaster i need your skype, so i can write with you there.

**Comment by Moonst** [comment]
defmaster if ya can give me a hand i dont know how to code but can play well would like your help with a brew profile not sure whats going on with chumii's it was doing great now all of a sudden im getting massive frame rates dropping and no lua errors again only happens when in raid. havent been able to try out ww yet

**Comment by Defmaster** [comment]
@ragnarger i will give you my Skype Name when i am back home 
@Moonst 
I replied in your extra issue . maybe i will do an overhaul in brewmaster too. But if it happen  out of nowhere, i think its another Problem which has nothing to do with the profile itself(or you changed something you dont expect to have an effect on it). But i will have a look. Its to bad that every profile has its own way of coding style :-(

**Comment by jawww** [comment]
i love the ww but there are some problems. the main problem is that the opeing rotation needs to use fists of fury before it uses serenity. also it seems to miss much too many fists of fury in the general rotation. fists of fury should be top prio

**Comment by jawww** [comment]
o ya and also i cant turn off auto sef

**Comment by Defmaster** [comment]
Hi jawww,

i am currently rewriting the ww profile and its nearly finished. Just need some polish and opening rotation . Profile will use current simc apl. When its finished i will push it to Badboy Master. It you want to try it, you can get the branch from my repo Defmaster/monk_ww_overhaul

**Comment by jawww** [comment]
that is awesome to hear!!!! so happy! :)

**Comment by Defmaster** [comment]
New completely rewritten WW profile is now pushed to master. Update BB to use it.
Not all options are implemented (NYI) tooltip. Stat buff auto-cast also not included yet.
Rotation is based 100% on SimC. Also uses opener Rotation with Chi Brew and Serenity selected.

Also if SEF is disabled, it will not cancel them like before. Only cancel SEF if it is on your current target.
Pause toggle currently -> Left-Shift/Alt/Ctrl 

You can now also differ more spells which spells to use with CD enabled. Try it and give feedback :)

**Comment by Moonst** [comment]
yeah i used it the other night it doesnt seem aoe was working was running skyreach norm and sef and aoe was on auto and it only did fists of fury i had to manually cast sef wich is ok just wondering if intended or not.

**Comment by Defmaster** [comment]
No it is not intended but unfortunatly it is a fh bug. 
Sometimes the object handler return nil values, which is why aoe doesn't work. Or enhancer spamming searing totem hehe. 
If it happens try a reload or close wow and reinject fh.

**Comment by Moonst** [comment]
kk thnx
