### ISSUE TITLE
How to judge the target of an unit which in the enemiesTable is me?

### ISSUE THREAD

**Issue by guiguziking** [BadBoy-Ultimate-Raider/BadBoy#132]
While I got an enemiesTable by function makeEnemiesTable(maxDistance), I only want to interrupt the casting unit which is target to me.
So, how to judge an unit's target is me? 
function UnitIsUnit(A,B) can't do this.

**Comment by ragnarger** [comment]
I dont know if I understand you correct. 
Do you want to interrupt your current target or do you want to interrupt any unit which casting something on you?

**Comment by chumiiger** [comment]
I think you would need to build a little workaround for this.
You can compare if UnitName("targettarget"), which is in the default wow api, is your name and then return true. You would just need to find a way to replace "targettarget" with "enemieTableEntry"-target if you get what I mean. target can be any UnitID, meaning it can be for example raid3target for the target of the third member in your raid, but I dont know how you would have to adapt it to the enemiesTable.. but maybe whis will get you in the right direction

have a look at http://wowprogramming.com/docs/api_types#unitID

**Comment by guiguziking** [comment]
I want to interrupt any unit which casting something on me in PVP, and do not choose this unit. 
I have solved this problem, like this:
ObjectName(UnitTarget(thisUnit)) == UnitName("player")
