### ISSUE TITLE
How to get the stealth unit ?

### ISSUE THREAD

**Issue by guiguziking** [BadBoy-Ultimate-Raider/BadBoy#133]
I found the function makeEnemiesTable(maxDistance) do not count the stealth unit, even modify the function getSanity(unit) in condition "if getSanity(thisUnit) == true then" like this:
    function mygetSanity(unit)
        if UnitExists(unit) and UnitCanAttack(unit, "player") == true and UnitIsDeadOrGhost(unit) == false then
            return true
        else
            return false
        end
    end

when I got a enemiesTable by function makeEnemiesTable(maxDistance) and print all unit, it can't print the stealth unit like Rouge or Invisibility Mage around me. But can print it while the Rouge lift the stealth.

How to solve this problem?

**Comment by ragnarger** [comment]
this is a good question ^^
afaik it is not possible... but maybe another one here knows sth.

**Comment by ragnarger** [comment]
you can play around with object manager from fh.

**Comment by Defmaster** [comment]
As far as i know, the client does not get any information about stealth units.

**Comment by ragnarger** [comment]
you cannot get the invisible units with the enemiesTable in the current way.
i dont have another person or 2nd active account to test things like this.

if i find someone or activate my 2nd acc sometimes i can test it. 

afaik it shall be possible with the object manager. there is someone coding pvp CR, saying he can do that.

**Comment by Defmaster** [comment]
That's what i said :smile: 
If there is an information in object manager from a stealth unit, theoretically just check if it has a Buff(Stealth)
To sad FH object manager isn't super reliable.

**Comment by guiguziking** [comment]
You are right,I can print it while the stealth Rouge near me when I can see it by eyes,about 5 yards.
but can't print Invisibility Mage while in 5 yards,because I can't see it by eyes.
The FH function GetObjectIndex() seems do not  get any information about stealth units except for the eye to see it.
So it's hard for hunter to cast Flare in advance.
