### ISSUE TITLE
The problem of Beastmaster stampede 

### ISSUE THREAD

**Issue by youzinvwangdaren** [BadBoy-Ultimate-Raider/BadBoy#134]
The 196th line of Beastmaster script
If castSpell ("player", Stampede, true, false) then        lead to the use of skills, this is wrong
It should be If castSpell ("target", Stampede, true, false) then         is right

**Comment by Defmaster** [comment]
Updated in my fixing branch.
Also "A Murder Of Crows" got fixed, had the same targeting problem.
