### ISSUE TITLE
delay on misdirection

### ISSUE THREAD

**Issue by cassrgs** [BadBoy-Ultimate-Raider/BadBoy#135]
Hello there
it is possible to put a little bit of delay after the cast of misdirection? the rotation keep casting it non stop for a few seconds on the pet when using the glyph

**Comment by guiguziking** [comment]
RunMacroText("/castsequence reset=1 misdirection,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11")

**Comment by Defmaster** [comment]
Fixed in my "MinorFixes" branch. 
It had no condition check if the buff is on you/pet, hence it casted continuously on BM profile.
