### ISSUE TITLE
brew mnk

### ISSUE THREAD

**Issue by Moonst** [BadBoy-Ultimate-Raider/BadBoy#136]
Hey chumii i tried swapping talents around and such with the brew profile and i noticed when i was using chi explosion keeping shuffle up was almost impossible and it was trying to only use a 2 chi explosion instead of three or 4. I think the only time we would use this talent would be on fights like iron maidens or beast lord or operator but it might be a nice addition but if it sacrifices survivability then i would say screw it lol. just a little tid bit to think about

**Comment by ragnarger** [comment]
chumii is inactive atm.
sry moonst

**Comment by Moonst** [comment]
oh kk np thnx for the reply

**Comment by Moonst** [comment]
if any one can check out the profile i was wondering why its lagging hard when im in a raid with 20 people it just started doing this but there are no errors

**Comment by Defmaster** [comment]
Will have a look at it,but dont have much time today. So could take some time. But if it just happen out of nowhere , i think it has nothing to do with the profile itself. Do you use  other talents or options with your brewmaster? Did it happen after a badboy update?

**Comment by Moonst** [comment]
na i was playing as normal doing garrison stuff and no lag then when i got in raid it started dropping the frame rates, but funny thing is it wasn't bad when i was out of sight of the people it only got bad when they were all on my screen meaning the raid was at beastlord and i was just around the corner from them and not a massive frame impact but when i went around the corner it drop the frame rates to 7fps. my norm is around 50-60 fps btw

**Comment by Moonst** [comment]
again thank you for all your doing

**Comment by ragnarger** [comment]
adjust Healing engine-> update rate one time.
maybe fix

**Comment by Defmaster** [comment]
I have tested BrM in a BG. Had no FPS drop. Like @ragnarger said try push update rate higher und check the box next to it to reduce update speed.
Only thing i found what's using group members is the "Stat buff" function, which is called when you check the option (ooc and incombat). Try to disable it. 
Does the FPS goes up when you disable Badboy in (just use the toggle) said situation?

**Comment by ragnarger** [comment]
you have to change it one time. else it is standard and refreshes every tick.
defmaster i have a izi pizi low cpu raidbuff check. look at shadow priest

**Comment by Defmaster** [comment]
Checked the Buff Functions, they are the same :D So it should be something different.

btw: You use local StaminaTable = {"Power Word: Fortitude","Blood Pact","Commanding Shout"}, would be better to use SpellID because of localisation.

**Comment by ragnarger** [comment]
yeah i know, but too lazy to change :D

**Comment by Moonst** [comment]
well i never had the buff function checked so i don't think its that and i turned the check all the way up on the healing engine and it got choppy but still reducing frame rates hrmm.

**Comment by Defmaster** [comment]
"Does the FPS goes up when you disable Badboy in (just use the toggle) said situation?"
Try that and report. 
FPS drop while going around the corner sounds more like a system/gpu/cpu/setting problem.

**Comment by Moonst** [comment]
yeah if im standing in the raid turn Badboy off and it smooths out fps raises i turn it on and drops like a rock and it is the same in combat or out when im around  the raid grp that is. all this is all done by using the toggle

**Comment by ragnarger** [comment]
i am looking through brewmaster code atm. i write down some things you can try.
write here, if smth brought you your fps back or not ^^
1) try to turn off autobuff
... found nothing else sry

**Comment by Moonst** [comment]
so i just tried out brew and its a bit better almost double the frame rate than before but i can still tell something is checking all raid members maybe detox or zen sphere I'm not sure, or maybe checking for threat all i know is the way i play i don't need the check I like to manually check raid members for buffs and cleanses and what not so I'm not sure though.

**Comment by ragnarger** [comment]
I made healing engine refresh static. That maybe brought some fps. 
Pls write me down all spells a monk uses on friendly targets / for friendly targets. I'll look on it in a few hours.

**Comment by Moonst** [comment]
Zen sphere, detox and legacy of the white tiger, the heal is surging mist, is there a way to disable the healing engine for certain profiles like a brew master?

**Comment by ragnarger** [comment]
I will look at it. I am already on the way home. Just wait a little bit.

**Comment by ragnarger** [comment]
i looked over the profile...
zen sphere isnt checking raid.
detox isnt checking raid. (you can enable/disable it in options)
lowt isnt available.

try to disable "Stats Buff" in the options

**Comment by Moonst** [comment]
stats buff is disabled and so is detox
Im just wondering if messing with the healing engine is increasing the frame rates does this specific profile need the healing engine?
and i want to thank you for all the work your doing

**Comment by ragnarger** [comment]
the healing engine is very heavy. i felt this by my own.
i could ad a switch for healing engine,... maybe...
we will see.
1) what are your FPS with BB deactivated?
2) what are your FPS with BB activated?
both values in the same situation.
3) are the fps dropping infight, outfight or in- and outfight?

**Comment by Moonst** [comment]
fps while bb not activated 40
fps while bb activated 14
this is in combat and out of combat as long as Im around a lot of people
if only a couple people even a 5 man my fps drops to about 25 or so; but only when in a group with them

**Comment by Defmaster** [comment]
Could you post your system config? cpu,gpu, etc.?

**Comment by Defmaster** [comment]
Raided tonight with monk alt as tank BRF HC 7/10. Doing 9/10 but had suboptimal group tonight.
Based on warcraftlogs.com i ranked @ over 90% for my item level bracket. Started with 662 and ended with 670. Also dmg was good ranked. Only 2 bosses which were not above 90% but around 80%.
Seems profile is in a good state, also had no fps drops.

**Comment by Moonst** [comment]
hrmm must be my comp ill check thru it see what is running in background if anything umm cant remeber command in the cmd prompt to get a system config run down

**Comment by Moonst** [comment]
so raided tonight with it an absolutely not a single prob. was great and i had a lot of fun

**Comment by Defmaster** [comment]
With new WW profile, i also changed some brewmaster things.
But should not affect you. Just disabled mouseover things like detox and rezz.
Also disabled stat buff during combat.
