### ISSUE TITLE
libdraw

### ISSUE THREAD

**Issue by cassrgs** [BadBoy-Ultimate-Raider/BadBoy#137]
Hello there folks
I'm getting the following error when tryng to use shadow priest

29x ...aceBadBoy\Rotations\Priest\Shadow\Shadow.lua:6: Cannot find a library instance of "LibDraw-1.0".
[C]: in function `error'
DataStore\libs\libstub\libstub.lua:38: in function `LibStub'
...aceBadBoy\Rotations\Priest\Shadow\Shadow.lua:6: in function `PriestShadow'
BadBoy\System\Core.lua:209: in function <BadBoy\System\Core.lua:149>

Locals:
self = <table> {
 NewLibrary = <function> defined @DataStore\libs\libstub\libstub.lua:20
 minors = <table> {
 }
 minor = 2
 IterateLibraries = <function> defined @DataStore\libs\libstub\libstub.lua:46
 GetLibrary = <function> defined @DataStore\libs\libstub\libstub.lua:36
 libs = <table> {
 }
}
major = "LibDraw-1.0"
silent = nil

maybe an addon conflict?

**Comment by ragnarger** [comment]
i will fix that this evening.

**Comment by ragnarger** [comment]
fixed
