### ISSUE TITLE
Not an issue just a profile question

### ISSUE THREAD

**Issue by Kiwical** [BadBoy-Ultimate-Raider/BadBoy#138]
Are these profiles still being worked on, i look at the list and many are still at the same % been a couple of months now, i know the creators have lifes outside of wow, im just wondering if profiles still working i havent subbed in a couple of months because of work commitments but now have found time to play and wanted to see if profiles still work for leveling and end game.

Thanks

**Comment by ragnarger** [comment]
which profile you want to use?
at the moment i am nearly the only one working on a profile atm... :(
some of us dont play wow at the moment, some others dont have that much time because of their job.

maybe i can make you a basic profile of a class you wanna use, DPS only pls ^^

i hope i could an will can help you

**Comment by Kiwical** [comment]
Wanted to level a Shadow priest from 15-100

**Comment by ragnarger** [comment]
shadow is working.
but just for lvl 100 :P

**Comment by ragnarger** [comment]
I could add a very simple rotation for leveling. I can not test it by myself because I do not have a low level priest. 
Do you level by questing or dungeons?
Do you want that?

**Comment by Kiwical** [comment]
that would be great i mostly do dungeons

**Comment by ragnarger** [comment]
okay i will do it the following days. 
but,... its just a very very simple rotation.
ok?

**Comment by Kiwical** [comment]
yep np just something to get me to 100 then i try proper profile

**Comment by ragnarger** [comment]
i will do that. i think it'll be finished and uploaded till sunday...

**Comment by Kiwical** [comment]
sweet all good thanks

**Comment by ragnarger** [comment]
sry you have to wait a few more days. so much to do with university

**Comment by Kiwical** [comment]
not a problem leveling a paladin,dk,monk atm

**Comment by ragnarger** [comment]
level rota added. activate it in options->utilities

**Comment by Kiwical** [comment]
sweet will give it a go this afternoon

**Comment by ragnarger** [comment]
u used it already?

**Comment by Kiwical** [comment]
No not yet hadn't had the time i only got to lvl 10 i will give it a shot sometime today if i finish work early

**Comment by Kiwical** [comment]
Doesnt work at lvl 10, what level will it start working at?

**Comment by ragnarger** [comment]
check options->utilities and activate level rotation

**Comment by Kiwical** [comment]
yep its activated im guessing it wont work until i get mind blast and d plague at level 21 cause it wont start at all for me im lvl 12 now

**Comment by Kiwical** [comment]
Im level 21 MB and D plague works so far
