### ISSUE TITLE
Boomkin updates

### ISSUE THREAD

**Issue by Kiwical** [BadBoy-Ultimate-Raider/BadBoy#142]
getting this error even though im not using the profile 

Interface\AddOns\BadBoy\Rotations\Druid\Moonkin\Boomkin.lua:27: '}' expected (to close '{' at line 4) near '='
Time: 05/12/15 10:33:28
Count: 1
Stack: [C]: ?
[C]: in function `LoadAddOn'
Interface\AddOns\AddonLoader\AddonLoader.lua:136: in function `LoadAddOn'
Interface\AddOns\AddonLoader\Conditions.lua:146: in function <Interface\AddOns\AddonLoader\Conditions.lua:134>
Interface\AddOns\AddonLoader\Conditions.lua:166: in function <Interface\AddOns\AddonLoader\Conditions.lua:153>

Locals: (*temporary) = "BadBoy"

**Comment by ragnarger** [comment]
boomkin is atm at a rework.
its not raidable atm and not ready to use.

sry for commiting but i have sometimes to change the computer and then i use a commit to move file from one machine to the other.

will be finished in a few days.
