### ISSUE TITLE
feral kitty

### ISSUE THREAD

**Issue by Moonst** [BadBoy-Ultimate-Raider/BadBoy#148]
been noticing on bosses seems all is working alright but on trash like aoe and such the auto detect isn't working and also using lunar inspiration messes with the use of thrash if this could be looked at i would appreciate it the rotation is awesome single target is really good just doesnt handle the object targets well i think thnx

**Comment by Kiwical** [comment]
I switched to bloodtalon as i had the same issue, and yeah the profile is pretty good it does sort of slip into auto attack sometimes i was farming steamweedle rep and now and again every few mobs it will just auto attack i have to press shred to kick it back into action again.

**Comment by Defmaster** [comment]
I will look into it when i am back home. But have no lvl 100 druid atm to test.

**Comment by Defmaster** [comment]
Could you please describe what the rotation is doing and what you would expect it to do?

And what happens before the rotations stops working for you @Kiwical ?

Trying to get into the code, but its some kind of a mess D:

**Comment by Kiwical** [comment]
For me it feels like its pooling energy for Ferocious Bite at full combo points when it does that it slips into auto attack sometimes not all the time though i usually have it on Auto for dps not multi or single

**Comment by Moonst** [comment]
yeah the slipping into auto atk it does it for me too especially when im changing targets a lot like on oregorger but pressing a button kicks it back into rotation i was talking about the aoe it doesnt seem to be useing thrash or swipe when multi. targets are around and yeah lunar messes with thrash if thrash is up it doesnt want to cast lunar if moonfire is up it doesnt want to cast thrash weird

**Comment by ragnarger** [comment]
maybe sth with timetodie?

**Comment by Moonst** [comment]
not sure ill use it a bit more and just use bloodtalons to see how it goes.

**Comment by Defmaster** [comment]
CuteOn is trying to refactor her code, aswell as I. Maybe we can catch the bug or whatever :+1:

**Comment by Moonst** [comment]
bloodtalons have been working great its just lunar talent thats not working so well but useing blood talons seems to be working awesome

**Comment by Kiwical** [comment]
Bit off class topic here, will interrupt for paladins get looked at, as it doesnt work at all for me, Ret pally profile its actually a really great profile i leveled 90-100 with it now im at 100 im starting to gear him

**Comment by Defmaster** [comment]
Ya i am gonna look into it, but next time start a new issue. Better for tracking and assigning.
