### ISSUE TITLE
Getting spammed with an error?

### ISSUE THREAD

**Issue by Specified** [BadBoy-Ultimate-Raider/BadBoy#149]
I'm raiding right now and using the feral profile, and getting spammed every few seconds by Bug Sack.
Can't quite figure it out at the moment, but I will paste the error.

Could anyone help me figure out what's going on, or what I can do to fix it?

354x BadBoy\System\readers\combatlog.lua:148: attempt to index global '_Queues' (a nil value)
BadBoy\System\readers\combatlog.lua:148: in function `common'
BadBoy\System\readers\combatlog.lua:48: in function <BadBoy\System\readers\combatlog.lua:43>

Locals:
self = <unnamed> {
 0 = <userdata>
}
event = "COMBAT_LOG_EVENT_UNFILTERED"
cl = <table> {
 enrageReader = <function> defined @BadBoy\System\readers\combatlog.lua:10
 Rogue = <function> defined @BadBoy\System\readers\combatlog.lua:376
 commonReaders = <function> defined @BadBoy\System\readers\common.lua:1
 debugTable = <table> {
 }
 Deathknight = <function> defined @BadBoy\System\readers\combatlog.lua:302
 Paladin = <function> defined @BadBoy\System\readers\combatlog.lua:367
 Shaman = <function> defined @BadBoy\System\readers\combatlog.lua:388
 common = <function> defined @BadBoy\System\readers\combatlog.lua:78
 enraged = <table> {
 }
 Mage = <function> defined @BadBoy\System\readers\combatlog.lua:316
 Warrior = <function> defined @BadBoy\System\readers\combatlog.lua:431
 Druid = <function> defined @BadBoy\System\readers\combatlog.lua:213
 Warlock = <function> defined @BadBoy\System\readers\combatlog.lua:401
 Priest = <function> defined @BadBoy\System\readers\combatlog.lua:363
 display = <function> defined @BadBoy\System\ui\debugelement.lua:31
 combatLog = <function> defined @BadBoy\System\readers\combatlog.lua:38
 Monk = <function> defined @BadBoy\System\readers\combatlog.lua:359
 Hunter = <function> defined @BadBoy\System\readers\combatlog.lua:304
}

**Comment by Defmaster** [comment]
I think Ragnar broke it by trying to fix queues. :-D 
Should not be a Problem to fix it.

**Comment by ragnarger** [comment]
i only changed the option check... because there was the wrong name for the option check in it.
i will look on the code now and try to find it.

**Comment by ragnarger** [comment]
the code after line 144 was never executed because of the wrong option check.

a fix workaround should be:
disable "Queue Casting" in the "General" Tab in the options.

**Comment by Specified** [comment]
Sorry it took forever for me to respond, but yes it was!
And it did fix it. Thank you so much, never occurred to me that would be the issue.
