### ISSUE TITLE
#getEnemies not working for me, anyone else?

### ISSUE THREAD

**Issue by popster** [BadBoy-Ultimate-Raider/BadBoy#150]
Recently returned back to game / badboy and found that the getEnemies function isn't working for me...

/dump #getEnemies("player",40)
returns 0 regardless of how many enemies i put myself around

/dump getEnemies("player",40)
returns empty table

fresh install, did I screw something up? Is their a new function for this?

Thanks

**Comment by ragnarger** [comment]
injected correctly?
what returns UnitName(ObjectPointer("Player"))

**Comment by popster** [comment]
maybe I downloaded an old version or something, reinstalled and it's working now... all good thx

**Comment by ragnarger** [comment]
sometimes FH isnt injecting correctly. then the distance im power button should appear in red color. restart wow and inject again.

**Comment by Defmaster** [comment]
I think i should do a bigger indicator like a big overlay so every one should See it :-D
