### ISSUE TITLE
Interrupts not working

### ISSUE THREAD

**Issue by Defmaster** [BadBoy-Ultimate-Raider/BadBoy#151]
**Interrupts are currently not working !**

They have **low prio** on our site, because in a raid environment it's hard to tell when to use it. Most guilds will have a kick rotation like on Oregorger. Most likely we will implement kicks for specific casts in raid, as we don't want it to be used in pvp.

For the time being use it *manually*.

**Comment by Kiwical** [comment]
This is true, i only manually use it when i do pvp but thats once in a blue moon as i have no interest in PvP what so either only to get REP for the ashran mount, but i get what ya saying, i think Soapbox did the same with his leveling rotations they only work in a PvE environment only not  pvp.
