### ISSUE TITLE
lastcast boolean function request 

### ISSUE THREAD

**Issue by popster** [BadBoy-Ultimate-Raider/BadBoy#152]
Can we get a lastcast('sepllid') booleans function? 

and in the meantime if anyone has a function they can give me to use I'd be most grateful

**Comment by Defmaster** [comment]
It's already implemented, but not as a function.
Variable "lastSpellCast" should contain the Spellid of last spellcast.

As I did not wrote that stuff, i cant guarantee its working correctly :D

**Comment by popster** [comment]
Thanks, it works but the fact you need to set everything to false for spam allowed can be problematic :( if a future update could add this to update for every spell regardless it would be gr8

**Comment by ragnarger** [comment]
you want a function that tells the last spell SUCCESS?

**Comment by ragnarger** [comment]
added:
lastSpellCast
lastSpellCastSuccess
variables.
lastSpellCast: last spell casted
lastSpellCastSuccess: last spell casted successful

**Comment by popster** [comment]
thanks man, you're a beast

**Comment by ragnarger** [comment]
np

**Comment by popster** [comment]
hate to bother more but wondering if there is any easy way to check the last TWO spells cast with this function?

something like secondLastSpellCast==spellid

which would return the second spell you started casting before your current one

tyvm

**Comment by ragnarger** [comment]
lol wtf :D
what is the reason you need this?

**Comment by popster** [comment]
cobra shot + steady focus for hunter... just using lastSpellCastSuccess causes it to sometimes chain cast Cobra Shot 3 times in a row before it can register that we now have the buff Steady Focus with the right amount of time remaining :(

**Comment by ragnarger** [comment]
ok... i'll do sth. just wait some minutes

**Comment by ragnarger** [comment]
added

**Comment by popster** [comment]
ty so much, my steady focus works perfect now ^^!

**Comment by ragnarger** [comment]
np
