### ISSUE TITLE
Ret pally error

### ISSUE THREAD

**Issue by Kiwical** [BadBoy-Ultimate-Raider/BadBoy#153]
Message: Interface\AddOns\BadBoy\System\GeneralFunctions.lua:100: Usage: UnitBuff("unit", [index] or ["name", "rank"][, "filter"])
Time: 06/17/15 17:51:34
Count: 26
Stack: [C]: in function `UnitBuff'
Interface\AddOns\BadBoy\System\GeneralFunctions.lua:100: in function `UnitBuffID'
Interface\AddOns\BadBoy\System\GeneralFunctions.lua:696: in function `getBuffStacks'
...adBoy\Rotations\Paladin\Retribution\cRetribution.lua:340: in function `castSelfLessHealer'
...oy\Rotations\Paladin\Retribution\retributionSimC.lua:17: in function `retributionSimC'
...adBoy\Rotations\Paladin\Retribution\cRetribution.lua:169: in function `startRotation'
...adBoy\Rotations\Paladin\Retribution\cRetribution.lua:67: in function `update'
...BadBoy\Rotations\Paladin\Retribution\Retribution.lua:31: in function `PaladinRetribution'
Interface\AddOns\BadBoy\System\Core.lua:190: in function <Interface\AddOns\BadBoy\System\Core.lua:153>

Locals: (*temporary) = "player"
(*temporary) = nil

**Comment by Defmaster** [comment]
Will look at it when iam home. Until then dont use selfless healer talent
