### ISSUE TITLE
Paladin issue?

### ISSUE THREAD

**Issue by Kiwical** [BadBoy-Ultimate-Raider/BadBoy#156]
ok forgive me for bringing an issue so fast after FH just coming back and it's expected i guess. 

Just noticing with the Ret paladin its casting word of glory every 1 holy power i was taking on a few mobs and my life was getting pretty low it would just attack to 1 holy power then cast WoG attack again WoG it was like it was looped i have the updated version of the profile.Even with alot of life it does still seem to cast WoG during the rotation

And my pally is fresh a 100 so im only around 630ilvl and im doing about 9k damage i dunno if thats normal or not it doesnt feel like alot i think because of amount of WoG it seems to be casting.

**Comment by Defmaster** [comment]
that should be the case, when you set the hp usage to 100, you have to adjust the hp when to use word of glory

**Comment by Defmaster** [comment]
i pushed a new commit, a condition wasnt correctly checked, now should use it if more or equal of 3 HP

**Comment by ragnarger** [comment]
Is the problem still there? 
It should be fixed.

**Comment by Kiwical** [comment]
Yeah fixed, thanks.
