### ISSUE TITLE
Feral Rotation

### ISSUE THREAD

**Issue by clfarmer88** [BadBoy-Ultimate-Raider/BadBoy#157]
Hey the feral rotation doesnt work at all, and when i inject FH the ui (paladin shield icon) disappears and makes it hard to try configure.

**Comment by ragnarger** [comment]
we are working on updates.
if a rotation doenst work, consider it as outdoated.
we have to do so much at the moment...
thx for bug report.

**Comment by Kiwical** [comment]
it sort of works for me, still  have to manually kick into gear sometimes

**Comment by clfarmer88** [comment]
what do you do to get it working?

**Comment by ragnarger** [comment]
Activate the bb Action log in options. Activate display fail casts. If it stucks make us a screenshot of the action log.

**Comment by clfarmer88** [comment]
Weirdest thing, i haven't changed anything and now its working after 2 days of it stuffing up. Anyway there is still the problem of the UI disappearing after FH is injected. I cant see any of the buttons that allow me to change the way i dps mid fight.

**Comment by ragnarger** [comment]
You have the bb button around your map. there are some click options explained when you mouse over it.

**Comment by Defmaster** [comment]
Will look at it when back home. But only  have 85 twink druid.

**Comment by clfarmer88** [comment]
thanks ragnarger and sorry for the noob questions xD

**Comment by Defmaster** [comment]
Cant reproduce the bug with my 85 feral. Please post LUA Error. (using BugSack, so you can view same better)

**Comment by clfarmer88** [comment]
just ran the rotations for 5 minutes with that addon and got no bugs. But it still isnt using Healing Touch when it used to for "Bloodtalons"

Incoming long error code which i got when FH first released their 6.2 version. Hope this might help. Just so you know this does NOT come up anymore.

Date: 2015-06-28 14:43:27
ID: 1
Error occured in: Global
Count: 1
Message: ...rface\AddOns\BadBoy\System\engines\HealingEngin e.lua line 227:
attempt to perform arithmetic on local 'x' (a boolean value)
Debug:
...rface\AddOns\BadBoy\System\engines\HealingEngin e.lua:227: GetPosition()
...rface\AddOns\BadBoy\System\engines\HealingEngin e.lua:275: UpdateUnit()
...rface\AddOns\BadBoy\System\engines\HealingEngin e.lua:353: Update()
BadBoy\BadBoy.lua:279: PulseUI()
BadBoy\System\Core.lua:166:
BadBoy\System\Core.lua:149
Locals:
self = <table> {
UpdateUnit = <function> defined @Interface\AddOns\BadBoy\System\engines\HealingEng ine.lua:244
guid = "Player-3723-09B528C7"
GetRole = <function> defined @Interface\AddOns\BadBoy\System\engines\HealingEng ine.lua:212
guidsh = "528C7"
unit = "player"
Dispel = <function> defined @Interface\AddOns\BadBoy\System\engines\HealingEng ine.lua:95
hpabs = 325320
target = "playertarget"
hpmissing = 0
absorb = 0
subgroup = 0
refresh = 222097.586
isPlayer = true
nGUID = <function> defined @Interface\AddOns\BadBoy\System\engines\HealingEng ine.lua:190
getUnitGroupNumber = <function> defined @Interface\AddOns\BadBoy\System\engines\HealingEng ine.lua:236
CalcHP = <function> defined @Interface\AddOns\BadBoy\System\engines\HealingEng ine.lua:111
name = "******"
class = "Druid"
GetPosition = <function> defined @Interface\AddOns\BadBoy\System\engines\HealingEng ine.lua:223
GetClass = <function> defined @Interface\AddOns\BadBoy\System\engines\HealingEng ine.lua:199
hp = 100
dispel = false
}
x = false
y = nil
z = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = false
(*temporary) = 2
(*temporary) = "attempt to perform arithmetic on local 'x' (a boolean value)"
o = <table> {
UpdateUnit = <function> defined @Interface\AddOns\BadBoy\System\engines\HealingEng ine.lua:244
guid = "Player-3723-09B528C7"
GetRole = <function> defined @Interface\AddOns\BadBoy\System\engines\HealingEng ine.lua:212
guidsh = "528C7"
unit = "player"
Dispel = <function> defined @Interface\AddOns\BadBoy\System\engines\HealingEng ine.lua:95
hpabs = 325320
target = "playertarget"
hpmissing = 0
absorb = 0
subgroup = 0
refresh = 222097.586
isPlayer = true
nGUID = <function> defined @Interface\AddOns\BadBoy\System\engines\HealingEng ine.lua:190
getUnitGroupNumber = <function> defined @Interface\AddOns\BadBoy\System\engines\HealingEng ine.lua:236
CalcHP = <function> defined @Interface\AddOns\BadBoy\System\engines\HealingEng ine.lua:111
name = "******"
class = "Druid"
GetPosition = <function> defined @Interface\AddOns\BadBoy\System\engines\HealingEng ine.lua:223
GetClass = <function> defined @Interface\AddOns\BadBoy\System\engines\HealingEng ine.lua:199
hp = 100
dispel = false
}
GetTime = <function> defined =[C]:-1

AddOns:
Swatter, v5.21d2.5561 (SanctimoniousSwamprat)
NPCScan, v6.2.0.1
Archy, v6.2.0.1
AskMrRobot, v25
AtlasLoot, vv8.00.30
Babylonian, v5.1.DEV.332(/embedded)
BadBoy, v1.0
BeanCounter, v5.21d2.5561 (SanctimoniousSwamprat)
BigWigs, v4.856
Configator, v5.1.DEV.382(/embedded)
DebugLib, v5.1.DEV.337(/embedded)
DroodFocus, v6.2.5
Enchantrix, v5.21d2.5561 (SanctimoniousSwamprat)
EnchantrixBarker, v5.21d2.5561 (SanctimoniousSwamprat)
GatherMate2, v1.33.5
HandyNotes, vv1.3.3
HandyNotesDraenorTreasures, v1.14
Informant, v5.21d2.5561 (SanctimoniousSwamprat)
LibExtraTip, v5.12.DEV.384(/embedded)
MapCoords, v0.21
MasterPlanA, v
Skada, v1.4-31
SlideBar, v5.21d2.5561 (SanctimoniousSwamprat)
Stubby, v5.21d2.5561 (SanctimoniousSwamprat)
TheUndermineJournal, v3.4.20150627
TipHelper, v5.12.DEV.380(/embedded)
BlizRuntimeLib_enUS v6.2.0.60200 <none>
(ck=37a)

**Comment by clfarmer88** [comment]
On another note i might be getting this error still bit cant tell as when i login blizzard tells me i have ui bug problems and they have given me that message instead of making them pop up on my screen.

**Comment by Defmaster** [comment]
yeah that was already fixed.

```
		-- Healing Touch
					if psRemain>0 and ((combo>=4 and bloodtalons) or psRemain<1.5) then
						if getOptionValue("Auto Heal")==1 then
		                    if castSpell(nNova[1].unit,ht,true,false,false) then return end
		                end
		                if getOptionValue("Auto Heal")==2 then
		                    if castSpell("player",ht,true,false,false) then return end
		                end
					end
```

That means, HT is used when:
predetory Swiftness is up AND (either) combo points more than 3 with blootalons talent OR if swiftness has less than 1.5sec remaining
then it checks for getOptionValue("Auto Heal"):
```
                    -- Dream of Cenarius Auto-Heal
                    if getTalent(6,2) then
                        checkOp("Auto Heal")
                        dropOp("Auto Heal", 1, "|cffFFFFFFSelect Target to Auto-Heal",
                            "|cffFFDD11LowestHP",
                            "|cffFFDD11Self")
                        textOp("Auto-Heal (DoC)")
                    end
```
So it can only be set when using above talent. When its set to 1 it will try so use it on a raidmember (and should use it on self when none present?! not sure)
If its set to 2, always the player gets the HT. If the talent isnt selected value == 0, and therefor no heal.
The other HT code:
```
-- Healing Touch
	            if isChecked("Healing Touch") 
	            	and ((psRemain>0 and php <= getOptionValue("Healing Touch")) 
	            		or (not isInCombat("player") and rejRemain>0 and php<=getOptionValue("Rejuvenation"))) 
	            then
	                if castSpell("player",ht,true,false,false) then return end
	            end
```
This will be used when Healing Touch is checked, and useDefensive is checked/toggled.
Then HT will be used when Predatory Swiftness is up and player HP are <= than selected HP%. 
Hope this helps you to identify the problem.

I set HT to checked, use defensive checked, and set hp. HT was used. Maybe its something with the Dream of Cenarius talent and its option?

**Comment by Defmaster** [comment]
I updated so you can set option checkOp("Auto Heal") even if not talented into (6,2)

**Comment by Neretil** [comment]
Hi Defmaster!
For me it works perfectly, thanks for the fix.
I got a question: it looks like the T18 set change our rotation a little, is there any chance you could update it? Maybe with an old/new rotation switch option for those without the set

**Comment by Defmaster** [comment]
Will have a look at it. :)

**Comment by Kiwical** [comment]
doesnt seem to want to use auto rejev i have it set around 70 it uses healing touch with the dream of cenarious talent

**Comment by Defmaster** [comment]
```
if useDefensive() and not stealth and not flight then
-- Rejuvenation
	if isChecked("Rejuvenation") and php <= getOptionValue("Rejuvenation") then
	    if not stealth and rejRemain==0 and ((not isInCombat("player")) or isKnown(erej)) then
	        if castSpell("player",rej,true,false,false) then return end
	    end
	end
```

Should use it when:
* Rejuvenation in options checked (NOT auto rejuvenation, this is for raidmember healing)
* your HP are below he threshold you set
* you are not in stealth or flight form and have defensives active
* you have no running rejuv buff on you 
* are not in combat or have the perk to use it in cat form

**Comment by Kiwical** [comment]
Yeah reason why it wasnt healing for me i wasnt using the bloodtalon talent,I was using Claws of Shirvallah which casts rejuventation but it wouldnt use the Dream of Cenarius.

**Comment by Defmaster** [comment]
OK, but i think no pve feral use that talent. 
And I now seem know what you  mean by kick into rotation. Sometimes it seems it does nothing, but it just pools energy. Level feral with the rotation at the moment. And it happens now and then, but it does not cap energy or the like.

**Comment by Kiwical** [comment]
Ive had it pool to 100 energy a few times i just back away from mob then come back and it starts back up, but yeah when its 5cap it will pool to around 80 energy then ferocious bite that's when it seems to like stop rotation sometimes like its waiting to hit around 80 energy

**Comment by Neretil** [comment]
Hi Defmaster!

I couldn't raid since a month, so im not sure in which upgrade did this happen, but the feral cooldown usage went broken. It was perfect until now, for example the opener was Rake->Incarnation->Shred until 5 CP -> Tigers Fury -> Berserk -> Rip->Shred. Or later in the fight the bot waited until the next Tigers Fury to pop everything. Tonight i saw all kind of weird things. It worked perfectly once or twice, then other times it just didn't pop the cooldowns at all, or didn't use Berserk only incarnation, or popped them at the absolute worst time etc. Could you look into this please? If you need more information i can make same dummy tests tonight.

**Comment by Defmaster** [comment]
Hm i did not change anything beside some T18 set conditions.

**Comment by Neretil** [comment]
Sadly it's really bugged for me. Some examples:
-On pull it doesn't use Berserk after Tigers Fury
-On pull 8 times out of 10 it doesn't use Rip
-Randomly doesn't refresh Rake
-Randomly doesn't use Blood Talons buff
-When the cooldowns are back it doesn't use Berserk again

**Comment by Defmaster** [comment]
Do you have 2p18 oder 4p18 ? When did it start do act weird ? What talents are you using? What does the ~~scouter say about his power level?~~ cast  debug frame say?

**Comment by Neretil** [comment]
- I don't have T18 set bonus (had to quit raiding just after i asked for the update)
- You updated the rotation, but i couldn't play for 3 weeks. When i came back i updated the bot and the problems started. So it's the update or maybe any other change after that in the next 3 weeks.
- I use the standard raiding build, Incarnation/Blood Talons
- I'll update this post with the debug frame tonight.

**Comment by Defmaster** [comment]
I will look into it when i got some spare time. But i did not touch cooldown usage like beserk. (atm berserk will only be used if tigers fury is up, maybe a desync causes the weird behaviour)

**Comment by Neretil** [comment]
Re. There is nothing in the debug frame. I think it's not an error, just some priority issue with Tigers Fury. In the old version the bot used Berserk instantly after Tigers Fury, but now for some reason the bot doesn't notice when Tigers Fury is used and doesn't pop Berserk.

And this desynchronizes everything, the bot doesn't apply Rip (it always did after TF->Berserk) in the opener, it doesn't use Blood Talons proc etc...

**Comment by Defmaster** [comment]
So here is the cooldown usage:

```LUA
if useCDs() and tfRemain>0 and power>60 and ttd >= 18 and (incBuff or not incarnation) then
 BERSERK
end

if ((not clearcast and powmax-power>=60) or powmax-power>=80) and ObjectExists(dynamicUnit.dyn5) then
 TIGERS_FURY
end

if useCDs() and berCooldown<10 and ttm>1 and tarDist<5 then
 INCARNATION
end
```

That means:
BERSERK will get used when: Tiger's Fury is up, you have more than 60 energy the target lives more than 18 seconds and you have incarnation up (if you specced for it)

TIGERS_FURY will get used: either you have not clearcast and energyMAX- current  energy is above 60 or above 80 and there is a target within 5yard

INCARNATION will get used when: BerserkCooldown is below 10 and time to max energy is above 1sec and target distance is under 5y (5y = melee range)

Maybe i hadnt specced incarnation? I did not use feral with inc, so maybe you can tell me if there is something wrong with it. I did not touch those lines so behaviour shouldnt changed since addition of t18 set lines.

**Comment by Kiwical** [comment]
Noticed cutie is back, after the latest new changes the rotation doesnt work at all :/ no errors it just doesn't start.

**Comment by CuteOne** [comment]
Feral was working for me and another person last night, sorry about Guardian - Defmaster has fixed my blunder on that.

**Comment by Kiwical** [comment]
Yeah works again thanks.
