### ISSUE TITLE
Request: CastGroundBestPosition

### ISSUE THREAD

**Issue by popster** [BadBoy-Ultimate-Raider/BadBoy#158]
Just so it's not forgotten: it would be out of this world to get a castground function that will take the enemies table, find the biggest cluster of units within the range of the AoE spell and then determine the best position on the ground to lay an AoE spell! 

Very critical for fights like Mannoroth and the imps, overall useful for every other fight

**Comment by ragnarger** [comment]
working on it atm

**Comment by ragnarger** [comment]
should be done. 
look at https://github.com/BadBoy-Ultimate-Raider/BadBoy/blob/master/Custom/Functions.lua#L25
