### ISSUE TITLE
Resto Druid auto focus problem

### ISSUE THREAD

**Issue by cukiemunster** [BadBoy-Ultimate-Raider/BadBoy#162]
I posted this in Skype also, but figured this would reach people easier. Basically with the current resto druid, it is swapping focus waaay too often and easily. If your targeting a boss or add, and it targets anyone besides the tanks it still swaps focus off the tank. Ideally it should only auto swap focus if the other tank is targeted, i.e. a tank swap.

https://github.com/BadBoy-Ultimate-Raider/BadBoy/commit/95cbba6ef0c1c0caf2888bc5bf08d53aacd83752 is the commit that changed the way this works.

**Comment by CuteOne** [comment]
We never did get to this did we cuk :(
