### ISSUE TITLE
Add random timer or delay to decurse?

### ISSUE THREAD

**Issue by cukiemunster** [BadBoy-Ultimate-Raider/BadBoy#163]
Currently the dispel abilities happen TOO fast, is it possible to add some sort of random delay? Ideally an option to select the delay would be nice, but understandable if this is too much work.

**Comment by ragnarger** [comment]
it is possible. atm i have exams, so i dont have much time beside learning and raiding.
def or i will take a look at it.
which sort of delay do you want:
- dec after x seconds the debuff is applied
- dec after x% of the debuff runtime (if 0 runtime decurse after y seconds the debuff is applied)
- dec x seconds the debuff runs out

**Comment by cukiemunster** [comment]
x-y seconds after applied, or even %-% left would work. Any sort of randomization and/or delay would be awesome!

**Comment by Defmaster** [comment]
I ll try to realize when i come back home today. Gonna make a % of debuff duration expired.

**Comment by Defmaster** [comment]
Report if the new added delay timer works.
