### ISSUE TITLE
Paladin - Ret broken

### ISSUE THREAD

**Issue by Neretil** [BadBoy-Ultimate-Raider/BadBoy#164]
Hi!

I updated my Badboy and the ret paladin profile gone broken.
Minibar buttons are gone, and fire icon right click gives an error message: 
"Badboy Start/Stop is Stopped in general options" (it is not)

**Comment by Defmaster** [comment]
Will look at it when I am back home.  As I have to prot, I don't ret often, but dunno how I broke it :-D 
Should be fixed in about 2 hours.

**Comment by Defmaster** [comment]
Fixed it.
Added baseOptions frome new Class Framework to ret, which atm uses old options init. and had not tested it, so it seems.
Now its fixed.
