### ISSUE TITLE
Guardian Druid seems broke

### ISSUE THREAD

**Issue by Kiwical** [BadBoy-Ultimate-Raider/BadBoy#165]
It used to work, now it just casts lacerate over and over then pulverize it will cast  thrash on aoe but doesnt use mangle at all

**Comment by Defmaster** [comment]
Hehe my druid got 100 couple days ago and wanted him as guardian.
Yes the rotation is far away from the feral one. I did some adjustments for myself, but i think i will push them to master. Mangle had low prio.

**Comment by Kiwical** [comment]
Yeah i just use the spec for Tanaan Jungle dailes for fun

**Comment by Kiwical** [comment]
getting this error 

Message: Interface\AddOns\BadBoy\System\GeneralFunctions.lua:100: Usage: UnitBuff("unit", [index] or ["name", "rank"][, "filter"])
Time: 08/23/15 13:49:20
Count: 702
Stack: [C]: in function `UnitBuff'
Interface\AddOns\BadBoy\System\GeneralFunctions.lua:100: in function `UnitBuffID'
...\AddOns\BadBoy\Rotations\Druid\Guardian\Guardian.lua:43: in function `DruidGuardian'
Interface\AddOns\BadBoy\System\Core.lua:273: in function <Interface\AddOns\BadBoy\System\Core.lua:153>

Locals: (*temporary) = "player"
(*temporary) = nil

only started getting this error after the feral profile stopped working.

**Comment by Defmaster** [comment]
yeah was a sideeffect by cutones changes.
had it fixed on local before, but did not commit it.
now its fixed, if nothing broke again lol
