### ISSUE TITLE
Just getting around to testing this and it crashes my wow with this error

### ISSUE THREAD

**Issue by klepp0906** [BadBoy-Ultimate-Raider/BadBoy#167]
This happened in the past with SBR however he fixed it.   It also happens with ccR (he also fixed it but his fix isnt/wasnt permanent)  Every time it gets updated (i think thats what cactuar said) it needs to have a line deleted to be functional without the error/crash again.   He didnt elaborate on what the line or where the line is "yet" but hopefully that points you guys in the proper direction.

I use SVUI which is based on elvui fwiw.  It messes up all the font (not sure what it has to do with font) but if i log in and see the font messed up, i know the rotation addon im using is going to cause a crash with this error sooner rather than later.  

without further adieu here it is..

Message: Interface\AddOns\SVUI_!Core\system\core.lua:498: attempt to call method 'explode' (a nil value)
Time: 09/15/15 21:18:54
Count: 1
Stack: Interface\AddOns\SVUI_!Core\system\core.lua:498: in function <Interface\AddOns\SVUI_!Core\system\core.lua:485>
Interface\AddOns\SVUI_!Core\system\core.lua:736: in function `VersionCheck'
Interface\AddOns\SVUI_!Core\system\core.lua:861: in function `Initialize'
...erface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:896: in function <...erface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:876>

Locals: value = "1.2.6"
lowMajor = 1
lowMinor = 1
lowPatch = 0
version = "1.2.6"
(*temporary) = nil
(*temporary) = "1.2.6"
(*temporary) = "."
(*temporary) = "attempt to call method 'explode' (a nil value)"
_removedeprecated = <function> defined @Interface\AddOns\SVUI_!Core\system\core.lua:476
type = <function> defined =[C]:-1
string = <table> {
 split = <function> defined =[C]:-1
 encode = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\LUA.lua:173
 match = <function> defined =[C]:-1
 gmatch = <function> defined =[C]:-1
 upper = <function> defined =[C]:-1
 gsub = <function> defined =[C]:-1
 format = <function> defined =[C]:-1
 decode = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\LUA.lua:192
 lower = <function> defined =[C]:-1
 sub = <function> defined =[C]:-1
 gfind = <function> defined =[C]:-1
 explode = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\LUA.lua:214
 rep = <function> defined =[C]:-1
 loadtable = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\LUA.lua:225
 char = <function> defined =[C]:-1
 rtgsub = <function> defined @Interface\FrameXML\RestrictedInfrastructure.lua:610
 join = <function> defined =[C]:-1
 reverse = <function> defined =[C]:-1
 byte = <function> defined =[C]:-1
 trim = <function> defined =[C]:-1
 len = <function> defined =[C]:-1
 find = <function> defined =[C]:-1
}
tostring = <function> defined =[C]:-1
unpack = <function> defined =[C]:-1
tonumber = <function> defined =[C]:-1
SVUILib = <table> {
 CheckProfiles = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:1309
 SetMasterProfile = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:1468
 CheckMasterProfile = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:1459
 ToggleDualProfile = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:1454
 Launch = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:1206
 RefreshPlugin = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:534
 CheckData = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:1435
 SaveSafeData = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:1431
 GetSafeData = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:1423
 Remove = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:1295
 NewGlobal = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:1442
 CurrentProfile = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:1318
 GetModuletable = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:594
 WipeDatabase = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:1405
 RefreshModule = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:529
 CheckDualProfile = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:1450
 WipeAllSharedData = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:1417
 ImportDatabase = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:1383
 ExportDatabase = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:1370
 LoadModuleOptions = <function> defined @Interface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registr

**Comment by klepp0906** [comment]
yea just gave it a run anyways (post error) and closed my entire wow.  hoping to get this working properly so i can offer insight on the monk rotation and migrate from other tools ive been using to use this+fh permanently :p 

thank you very much for all your time and hard work put into this btw.  its very good looking/comprehensive in its presentation, now i just gotta put it to work :)

**Comment by klepp0906** [comment]
also icon under minimap is blank :P lol

**Comment by ragnarger** [comment]
i dont think we will fix this.
sry...

**Comment by klepp0906** [comment]
No need to apologize, it's free.  That being said, this effects tukUI and elvUI as well and between the 3 you have the largest chunk of the UI demographic in the game among raiders at least.

(Which is why soap fixed it)

Leaving it means alienating your main demographic or forcing them to revert to the default UI when they raid.  Crazy to me, but what do I know.

To be fair, it's my understanding this is a problem with the unlocking method being used and not the addon.  (In this case FH)

loldk is aware and has asked me to run a few commands in attempt to dial in on it.

I didn't know this prior to making this post.  I could potentially use a different unlocker with badboy and have no problems at all.  Will have to test and find out :)

Thank you for the reply regardless of ability to fix or not.  Very cool of you!

**Comment by CuteOne** [comment]
For what its worth I use a completely revamped UI as well with over 300
addons (near 200 active) and have not had issues.

**Comment by klepp0906** [comment]
Yea it's something innate between FH and similar unlockers & elvUI (or UI mods based on elvUI)

**Comment by klepp0906** [comment]
Thanks for all your hard work guys <3

**Comment by Defmaster** [comment]
I use ElvUI + a lot more addons. Never get such error.
Only TSM (TradeSkillMaster) throws an error for its securehook functions when used an unlocker.

**Comment by klepp0906** [comment]
Cool story bro.  I'll raise you a "I haven't had any issue with tsm" yet anyways.

Most do - Google it. The error is already listed.  If soap didn't censor his forums I'd link a thread that had people up in arms about it for ages (until he fixed it) at first he said the same thing, he didn't want to.

I've already been in touch with Mung (the svui dev) and cactuar (ccr dev) as well as loldk (fh dev) all have confirmed the same thing (that it's the fault of the unlocker) not sure which you use.  

It could even be feature dependent.  I was told by cactuar that simply deleting the line of code in the error will fix it but it will have to be re deleted every time.

Loldk gave me a command to run (can't post here as its in Skype and I'm not home) but will link later as he is trying to fix it.

For those with knowledge in such matters perhaps that will explain where or what he believes the issue to be.

I raid in a top 100 guild so I don't have a lot of time to test unfortunately, but when I do I'll add the results of running said code as well as the deletion as a temp solution.

Either way, as I've said it doesn't seem to be an issue with badboy itself nor ccr nor any of the rotation Addons, just the unlocking method used.

I'm guessing those outside of fh (and previously soap as it was my understanding he used FH or something very similar) issues are non existent.

Have a good day!
