### ISSUE TITLE
Problem about Font

### ISSUE THREAD

**Issue by guiguziking** [BadBoy-Ultimate-Raider/BadBoy#173]
Hi,  Defmaster, I'm really sorry to trouble you again. I tried to translate the UI into Chinese, eg:
Only to replace Line 371 of file cRetribution.lua:

createNewSpinner(section, "Divine Protection", 75, 0, 100, 1, "|cffFFBB00Under what |cffFF0000%HP|cffFFBB00 to use \n|cffFFFFFFDivine Protection")

with:
createNewSpinner(section, "圣佑术", 75, 0, 100, 1, "|cffFFBB00低于 |cffFF0000%血|cffFFBB00 使用 \n|cffFFFFFF圣佑术")

The result is the text   "圣佑术" on UI displays "???" and the tooltip "低于%血使用圣佑术" displays normally.
It's the same problem with the first parameter of function createNewWindow and function createNewProfileWindow. and the second parameter of function createNewSpinner, createNewCheckbox, createNewSpinnerWithout, createNewDropdownWithout, createNewSection, createNewText.

**Comment by Defmaster** [comment]
I had a first glance at it.
It seems that either the font does not support chinese or the height is to low.
WoW just put ??? if it cant display a letter if its to big for its destination.
Will look closer, but cant guarantee to fix it.

**Comment by guiguziking** [comment]
May be it's the problem of height, because the tooltip "低于%血使用圣佑术" displays normally.
The previous vision of badboy without newui is displays normally too.

**Comment by Defmaster** [comment]
So.
I tested:
- different font
- more padding between the toggles/elements
- bigger font
Nothing worked. I think its a thing with DiesalStyle itself. When using "Overlay" it also displayes correctly on the chat overlay even if its "???" within the frame.
But i have no idea how to fix that :-/

**Comment by guiguziking** [comment]
Thank you all the same. I‘ll wait for an answer.
