### ISSUE TITLE
Feral Druid Help

### ISSUE THREAD

**Issue by Chifo77** [BadBoy-Ultimate-Raider/BadBoy#174]
Hi can you pls help me on the Feral Talent´s for the CuteOne,

The Old Rotations is W/O last updates or what is the Diference? 

Tks

**Comment by CuteOne** [comment]
Old rotation is just that old, the talents I use are Feline Swiftness,
Ysera's Gift, Typhoon, Incarnation, Mighty Bash, Dream of Cenarius, and
Bloodtalons. I try my best to code for every spell so if something is not
working for you please let me know and I will see what I can do about
resolving it.

**Comment by Chifo77** [comment]
Hi, tks for the info, some times I use Nature's Vigil is that talent sported?
What about glyphs I m using the cat form or ninth life , Savage Roar and ferocious Bite

Date: Wed, 2 Dec 2015 15:19:01 -0800

**Comment by Chifo77** [comment]
Tks a lot for the info....

I use Nature´s Vigil Insted of DoC, is NV works?

What glifs do u recommend with the rotation ??

I choose between Glyph of Cat Form and Glyph of the Ninth Life, Glyph of Savage Roar And Glyph of Ferocious Bite....

Tks for the help

**Comment by CuteOne** [comment]
Again, I like to code things so they work regardless of player's choice so
if something isn't working then please give me the specifics and I will see
about fixing it.

I have confirmed Nature's Vigil works, it is utilized as a Defensive
ability and can be configured under the Defensive section of the options.
As for glyphs I personally use Major: Savage Roar, Cat Form, Rebirth,
Minor: Aquatic Form, Orca, Stag.
