### ISSUE TITLE
Is the Profile Status up to date???

### ISSUE THREAD

**Issue by Chifo77** [BadBoy-Ultimate-Raider/BadBoy#175]
Hi, i just want to know if the Profile status is up to date for all the BB rotations

Tks and Love ur Dk and Dudu Profiles :)

**Comment by Defmaster** [comment]
Most of them are - Frost DK, Enhancement, Arms Warrior, Windwalker, got some more changes.
Besides that,the status is up-to-date as there are not many developers for the rotations :/

The very best ones should be:
- Shadow
- Paladin (Ret and Prot (mainly doin prot and running very high ranks with it))
- Feral
Others doing ok, but lacking here and there (like overhauling frost dk, ww, enh).
And some are just shit for raiding or like warlock non-existent.

**Comment by ragnarger** [comment]
What rotation you want to usw?

**Comment by CuteOne** [comment]
Frost DK, WW, and Enhancement all should be raid usable (I and people I
know are using them in raids)

**Comment by Chifo77** [comment]
Tks for the info!!!!!

Im using Paladin, Dudus and Dk ones, and i want to use the Mage and Monk heal & tank...

**Comment by Defmaster** [comment]
Mage - just okayish for questing (sometimes no correct burn phase arcane, frost no pet usage for FoF procs, fire dont know)
Monk Tank - good for raiding, used the profile back in BRF; but has no T18 Stuff for set etc
Monk Heal - dont know

**Comment by CuteOne** [comment]
Closing
