### ISSUE TITLE
monk not working

### ISSUE THREAD

**Issue by leaderquebec** [BadBoy-Ultimate-Raider/BadBoy#177]
nnot working patch 7.0.3 addon disable

**Comment by CuteOne** [comment]
Can you give any more details, I assume you are referring to Windwalker?

**Comment by leaderquebec** [comment]
yes i need put on (test dps) for start dps and after kill the target addon stop working i got a error and blizzard ask turn off the addon

**Comment by leaderquebec** [comment]
![wowscrnshot_083116_012115](https://cloud.githubusercontent.com/assets/11083735/18124905/38e2acda-6f42-11e6-9b3f-a6e221fb4bfc.jpg)

**Comment by CuteOne** [comment]
Yea I decided to level monk to where i get the artifact weapons and did notice a few issues ones i got them, I will be pushing an update soon.

**Comment by CuteOne** [comment]
Ok try that, just pushed the update.

**Comment by leaderquebec** [comment]
okay thank you

**Comment by leaderquebec** [comment]
Works great

**Comment by CuteOne** [comment]
Awesome, glad that worked out for you...closing issue,

**Comment by NatPagles** [comment]
Having the same issue, wont use the rotation unless I leave the test dps dummy option checked.

**Comment by CuteOne** [comment]
Having the test dps option on shouldnt hurt anything but I will investigate this.

**Comment by CuteOne** [comment]
This is now fixed, thanks for the report.
