### ISSUE TITLE
why the combat routine does not work.

### ISSUE THREAD

**Issue by zy4944796** [BadBoy-Ultimate-Raider/BadBoy#180]
does the combat routine work fine for wow7.0.3?my character does not fight against the enemy any way.i am sure that  the add-on is loaded successfully,but it does not work fine until now.do i forget something necessary to set ?
my step:
1,copy the badboy-master to the wow's addones folder->2rename the badboy-master to badboy->3,restart wow,check badboy the status in the plugin UI list->4 click the flame icon on or off->run ewt->set ewt advanced lua unlock.
but ,the combat routine doesnot work any way.
i  get stuck here several hours,is there any solution ?
thanks.

**Comment by Defmaster** [comment]
The biggest question you did not answer is: Which spec do you use?
Not all are supported yet.

**Comment by CuteOne** [comment]
Correct not all specs are legion supported, there are very few people actively working on them at this time so I apologize for not having your spec already done As of this writing the following specs are supported:
Feral
Windwalker
Havoc - To Level 100
Enhancement
All Rogues - To Level 50
Retribution - To Level 10
Shadow - Unknown but work ha been done on it

**Comment by zy4944796** [comment]
@Defmaster @CuteOne thank your replys ,this is my fault ,i did not see the spec  statement list below the page,
Best regrads to all yours.
