### ISSUE TITLE
how much for Mistweaver

### ISSUE THREAD

**Issue by leaderquebec** [BadBoy-Ultimate-Raider/BadBoy#182]
How Much for Mistweaver Monk Work in dungeon ?

**Comment by CuteOne** [comment]
I am not sure, most of my knowledge is with DPS profiles unless one of the other devs makes it. I myself can not give a time frame on when this can be accomplished on my end... I suppose if there was someone to assist with healer logic (I have never and will never heal) and threw some money then one could be developed sooner.

Anyways that's my rambling response.
