### ISSUE TITLE
DH chat spam

### ISSUE THREAD

**Issue by matic33** [BadBoy-Ultimate-Raider/BadBoy#190]
everytime i start dh havoc profile, my ewt start spamming no-knockback disable, i can't read my chat anymore.
i only got this with dh, all the other profiles works fine

**Comment by CuteOne** [comment]
Another person had this issue with EWT, if you edit HavocCuteOne.lua line
194 change:

if IsHackEnabled("NoKnockback") ~= nil then SetHackEnabled("NoKnockback",
false) end

to

--if IsHackEnabled("NoKnockback") ~= nil then SetHackEnabled("NoKnockback",
false) end

this will prevent the error until I can find a solution.

**Comment by matic33** [comment]
thx, it works now :)
