### ISSUE TITLE
Demonology Warlock: uses Demonwrath as filler even though only 1 target is present

### ISSUE THREAD

**Issue by xenf** [BadBoy-Ultimate-Raider/BadBoy#191]
Rotation is functional but simc apl spams demonwrath as the filler instead of demonbolt/shadow bolt when only 1 mob is present.

Another error which happens to me is an LUA error for cooldown usages on bosses only.

Thanks

**Comment by CuteOne** [comment]
I will make that change to demonwrath, do you have a copy of the specific error for cooldown usage?

**Comment by xenf** [comment]
It isn't throwing the error anymore, perhaps it was an isolated incident with certain options

**Comment by CuteOne** [comment]
Love the feedback, I will continue to work on this and pay close attention to the issues you brought up.

**Comment by CuteOne** [comment]
I have been thinking about how best to control the Demonic Empowerment spams while adhereing to the following SimC lines:

```
 demonic_empowerment,if=wild_imp_no_de>3|prev_gcd.hand_of_guldan
demonic_empowerment,if=dreadstalker_no_de>0|darkglare_no_de>0|doomguard_no_de>0|infernal_no_de>0|service_no_de>0`
```

**Comment by kobasichoni** [comment]
The best guide on the rotation and talents for the demo lock Ive found is a video Im going to link. The guy is going realy in depth what and when to do so maybe we ciuld work the rotation around it. Like summon dreadstalkers-empower,hand of gouldan-empower etc. The rotation explanation starts at 11 minutes
https://youtu.be/MIHr2G_NPaM

**Comment by kobasichoni** [comment]
Any update on this? Ive run hov now and still bot us using demonwrath on singletarget where it should be using demonbolt

**Comment by CuteOne** [comment]
It should only be Demonwrathing if....
1) There are 3 or more targets in range of your pet
2) You are moving
3) You have more than 60% mana
