### ISSUE TITLE
Hotkey option

### ISSUE THREAD

**Issue by kobasichoni** [BadBoy-Ultimate-Raider/BadBoy#193]
Hey I wrote you on Ownedcore and kinda "requested" or asked if it is possible and you were very kind and not getting offended by it :) I was thinking about creating a macro to turn on/off BadBoy so I dont have to hold Shift pressed for pause or klick an icon. the same for CDs. I make a macro ingame that when pressed once it activates/deactivates CDs or Turns BadBoy on/off. if you understand my bad english....

**Comment by xenf** [comment]
Shift click the icon to open the toolbar and you can turn it off and on there with the first icon

**Comment by bfwlegend** [comment]
There's already a macro to toggles BadBoy, it's "/BadBoy"
https://github.com/BadBoy-Ultimate-Raider/BadBoy/blob/33dd90a5b490427613fdfeede25e3fbfa85130cd/BadBoy.lua#L193

**Comment by kobasichoni** [comment]
Hey thats the thing i was looking for :) cheers! Next thing ive noticed is that ww monk has lua errors when cds are set to automatic and when you use thenoptions to not brake cc and careful targeting. I would love to know if its only on my side or does anyone else have the same lua errors

**Comment by bfwlegend** [comment]
Please post the Lua errors, can't do much without them

**Comment by kobasichoni** [comment]
ok this first one is when you check dont break cc

Interface\AddOns\BadBoy\System\GeneralFunctions.lua:194: Usage: UnitDebuff("unit", [index] or ["name", "rank"][, "filter"])
Time: 10/12/16 21:00:30
Count: 65
Stack: [C]: ?
[C]: in function `UnitDebuff'
Interface\AddOns\BadBoy\System\GeneralFunctions.lua:194: in function `UnitDebuffID'
...rface\AddOns\BadBoy\System\engines\EnemiesEngine.lua:364: in function `isLongTimeCCed'
...rface\AddOns\BadBoy\System\engines\EnemiesEngine.lua:85: in function `makeEnemiesTable'
Interface\AddOns\BadBoy\BadBoy.lua:318: in function `makeEnTable'
Interface\AddOns\BadBoy\BadBoy.lua:344: in function `PulseUI'
Interface\AddOns\BadBoy\System\Core.lua:262: in function <Interface\AddOns\BadBoy\System\Core.lua:245>

Locals:

**Comment by kobasichoni** [comment]
this one is when you make macro to toggle aoe "/aoe"

Message: Interface\AddOns\BadBoy\System\UI.lua:33: attempt to get length of field '?' (a nil value)
Time: 10/12/16 21:03:16
Count: 1
Stack: [C]: ?
Interface\AddOns\BadBoy\System\UI.lua:33: in function `ToggleValue'
Interface\AddOns\BadBoy\BadBoy.lua:207: in function `?'
Interface\FrameXML\ChatFrame.lua:4332: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4000: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:2631: in function <Interface\FrameXML\ChatFrame.lua:2624>
[C]: ?
[string "C:\Users\PC\Desktop\FIRE\Lua\Always Facing...."]:94: in function <[string "C:\Users\PC\Desktop\FIRE\Lua\Always Facing...."]:84>
[string "C:\Users\PC\Desktop\FIRE\Lua\Events.lua"]:188: in function <[string "C:\Users\PC\Desktop\FIRE\Lua\Events.lua"]:182>
[string "Moving Cast.lua"]:138: in function `UseAction'
Interface\FrameXML\SecureTemplates.lua:348: in function `handler'
Interface\FrameXML\SecureTemplates.lua:621: in function <Interface\FrameXML\SecureTemplates.lua:569>
[C]: ?
Interface\FrameXML\SecureHandlers.lua:264: in function <Interface\FrameXML\SecureHandlers.lua:261>
[C]: ?
Interface\FrameXML\SecureHandlers.lua:294: in function <Interface\FrameXML\SecureHandlers.lua:277>
(tail call): ?

Locals:

**Comment by kobasichoni** [comment]
and this one is for cds

Message: Interface\AddOns\BadBoy\System\UI.lua:33: attempt to get length of field '?' (a nil value)
Time: 10/12/16 21:11:45
Count: 1
Stack: [C]: ?
Interface\AddOns\BadBoy\System\UI.lua:33: in function `ToggleValue'
Interface\AddOns\BadBoy\BadBoy.lua:216: in function `?'
Interface\FrameXML\ChatFrame.lua:4332: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4000: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:2631: in function <Interface\FrameXML\ChatFrame.lua:2624>
[C]: ?
[string "C:\Users\PC\Desktop\FIRE\Lua\Always Facing...."]:94: in function <[string "C:\Users\PC\Desktop\FIRE\Lua\Always Facing...."]:84>
[string "C:\Users\PC\Desktop\FIRE\Lua\Events.lua"]:188: in function <[string "C:\Users\PC\Desktop\FIRE\Lua\Events.lua"]:182>
[string "Moving Cast.lua"]:138: in function `UseAction'
Interface\FrameXML\SecureTemplates.lua:348: in function `handler'
Interface\FrameXML\SecureTemplates.lua:621: in function <Interface\FrameXML\SecureTemplates.lua:569>
[C]: ?
Interface\FrameXML\SecureHandlers.lua:264: in function <Interface\FrameXML\SecureHandlers.lua:261>
[C]: ?
Interface\FrameXML\SecureHandlers.lua:294: in function <Interface\FrameXML\SecureHandlers.lua:277>
(tail call): ?

Locals:

**Comment by kobasichoni** [comment]
and a random one during combat
Message: Interface\AddOns\BadBoy\System\UI.lua:33: attempt to get length of field '?' (a nil value)
Time: 10/12/16 21:16:18
Count: 3
Stack: [C]: ?
Interface\AddOns\BadBoy\System\UI.lua:33: in function `ToggleValue'
Interface\AddOns\BadBoy\BadBoy.lua:216: in function `?'
Interface\FrameXML\ChatFrame.lua:4332: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4000: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:2631: in function <Interface\FrameXML\ChatFrame.lua:2624>
[C]: ?
[string "C:\Users\PC\Desktop\FIRE\Lua\Always Facing...."]:94: in function <[string "C:\Users\PC\Desktop\FIRE\Lua\Always Facing...."]:84>
[string "C:\Users\PC\Desktop\FIRE\Lua\Events.lua"]:188: in function <[string "C:\Users\PC\Desktop\FIRE\Lua\Events.lua"]:182>
[string "Moving Cast.lua"]:138: in function `UseAction'
Interface\FrameXML\SecureTemplates.lua:348: in function `handler'
Interface\FrameXML\SecureTemplates.lua:621: in function <Interface\FrameXML\SecureTemplates.lua:569>
[C]: ?
Interface\FrameXML\SecureHandlers.lua:264: in function <Interface\FrameXML\SecureHandlers.lua:261>
[C]: ?
Interface\FrameXML\SecureHandlers.lua:294: in function <Interface\FrameXML\SecureHandlers.lua:277>
(tail call): ?

Locals:

**Comment by CuteOne** [comment]
Don't break CC option is currently broken :(
The aoe and cd macro toggles are also pretty old code and likely also don't work but with these error reports we will do what we can to solve the issue.

**Comment by kobasichoni** [comment]
cheers!

**Comment by CuteOne** [comment]
Fixed the issues with those errors and the slash comments, added /bbhelp to see list of commands that are available.

**Comment by kobasichoni** [comment]
Great to hear! I will test it to ight when i get back from work. SimC rotation had dome hickups wherenit lost stacks of combo strikes,where AMR works great. I will have to wait till I hit max lvl to test it in mythic dungeons and raids but i am sure it will do very well

**Comment by CuteOne** [comment]
If everything is fine then I will close this ticket.
