### ISSUE TITLE
resto druid

### ISSUE THREAD

**Issue by ugfodin** [BadBoy-Ultimate-Raider/BadBoy#195]
Hi,
i'd like to learn lua and try to make a resto druid for starters.
There's a problem when i switch to resto ingame, it doesn't load resto rotations( same for guardian and balance )

`149x BadBoy\System\Core.lua:370: attempt to call global 'DruidRestoration' (a nil value)`
`BadBoy\System\Core.lua:370: in function <BadBoy\System\Core.lua:245>`

`Locals:`
`self = <unnamed> {`
`0 = <userdata>`
`}`
`playerClass = 11`
`playerSpec = 4`
`playerLevel = 110`
`(*temporary) = nil`
`(*temporary) = "attempt to call global 'DruidRestoration' (a nil value)"`

It would be great if you could fix it so resto would start up when switching specs.
I'm loosing my way probably cause its such a big project and i think it'll be easier to start learning with just the rotations part to worry about.

**Comment by CuteOne** [comment]
I would be more than happy to guide you in making a Resto Druid profile, feel free to message me on Discord (Kynasha#8840).
