### ISSUE TITLE
Its not an issue its a question :)

### ISSUE THREAD

**Issue by kobasichoni** [BadBoy-Ultimate-Raider/BadBoy#196]
Howdy, I would like to ask how good are the rogue profiles? I see they are 100% but doesnt say if they are raid ready or not,can anyone tell me if they are good enough for competitive raiding/dungeons?

**Comment by CuteOne** [comment]
Recently did a few bug fixes on Assassination/Outlaw, my personal rogue is only 103, that said you are more than welcome to try them out and let me know of any problems you have (always happy to try my best to fix and improve)
