### ISSUE TITLE
Ww monk simc broken

### ISSUE THREAD

**Issue by kobasichoni** [BadBoy-Ultimate-Raider/BadBoy#197]
Hey could you check the simc rotation on ww monk please? It stops until you manualy press tiger palm and loses the buff by casting same ability twice in a row.

**Comment by CuteOne** [comment]
When did you last update, I implemented a fix to cast Tiger Palm in the event you did not have enough chi for anything...even if it was last cast. I was leveling (103-106) all last night on my monk. Not saying you're wrong just making sure. :)

**Comment by kobasichoni** [comment]
yep,youre right,I didnt update :) Thank you for the fix,rotations are awesome!

**Comment by CuteOne** [comment]
Closing
