### ISSUE TITLE
Ww monk

### ISSUE THREAD

**Issue by kobasichoni** [BadBoy-Ultimate-Raider/BadBoy#199]
Im playing ww monk and noticed that very oft he uses blackout kick 2 times in a row and looses the  buff,could you please fix that if it doesnt take you too much time :) rotation is a beast ive been wooping some better geared players on dmg meters in dungeons

**Comment by CuteOne** [comment]
I've added a check for when the buff is lost to report the spell that caused it and so far I have not had a report. Not sure why you are having problems, the code shouldn't allow for a double blackout kick, it does allow for a double tiger palm in the event there is no chi.

**Comment by kobasichoni** [comment]
Is there anything i can do to help you reproduce the bug? Because im seeing it very oft

**Comment by kobasichoni** [comment]
Hey I recorded it with my phone and uploaded on a random yt acc just to show you,maybe you can check it out :)   https://youtu.be/Eag6MOYlKbA

**Comment by CuteOne** [comment]
Clear as day....that is very odd, is there any chance you haven't updated in like a week or more?

**Comment by kobasichoni** [comment]
I downloaded yesterday

**Comment by kobasichoni** [comment]
I will trz one more time with clear cashe and all and will let you know

**Comment by kobasichoni** [comment]
wasnt there a ddos attack on some sites? I think this one was offline aswel,maybe they did a restore point before your fixes or something dunno...

**Comment by CuteOne** [comment]
there was but i dont have new updates for Windwalker and have been on the spec for the past few days (leveling and gearing up for raids)

**Comment by CuteOne** [comment]
Can you show me your Bot, Profile, and Toggle settings?

**Comment by kobasichoni** [comment]
Sure let me just try it now when i cleared all and downloaded new

**Comment by kobasichoni** [comment]
Damn now more than before :)

**Comment by kobasichoni** [comment]
Lemme just screenshot it for you

**Comment by kobasichoni** [comment]
https://postimg.org/image/vfl53x72t/

**Comment by CuteOne** [comment]
All that should be fine, are you still having the issue after resetting the files?

**Comment by kobasichoni** [comment]
Yes ofter than before

**Comment by CuteOne** [comment]
Ok I went ahead and pushed an update, this has a check for when hit combo stacks are lost, care to update again?

**Comment by kobasichoni** [comment]
Yes gimme a sec

**Comment by kobasichoni** [comment]
dang it its doing it 3 times now

**Comment by kobasichoni** [comment]
https://youtu.be/BVRUW_rWfA8

**Comment by CuteOne** [comment]
I see and still I don't see how that its even possible....if you are comfortable editing code then add the following line to WindwalkerCuteOne at line 232
`print(tostring(lastSpell))`

**Comment by kobasichoni** [comment]
I have never ever ever ever done something like that in my life,but id you tell me how i will do it no prob

**Comment by CuteOne** [comment]
ohh also do you have any error grabbing addon like BugSack or Swatter?

**Comment by kobasichoni** [comment]
No i dont,should i get it?

**Comment by CuteOne** [comment]
Please that may hold the key to the problem

**Comment by kobasichoni** [comment]
Okey gimme few mins i will do it

**Comment by kobasichoni** [comment]
ok I have bugGrabber do I need anything else

**Comment by CuteOne** [comment]
BugSack (i think they work in conjunction)

**Comment by kobasichoni** [comment]
Ok ima give it a test ride and see what we get

**Comment by kobasichoni** [comment]
2x BadBoy\System\Core.lua:171: attempt to index field '?' (a nil value)
BadBoy\System\Core.lua:171: in function `savePosition'
BadBoy\System\Core.lua:194: in function `saveWindowPosition'
BadBoy\System\Core.lua:221: in function <BadBoy\System\Core.lua:197>

Locals:
self = "config"
windowName = nil
(*temporary) = nil
(*temporary) = "Windwalker"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"

**Comment by CuteOne** [comment]
Another odd error but nothing that should cause a problem at least not that I would thing

**Comment by kobasichoni** [comment]
Well guess I will get my shamy to max level and play him if you say it works perfect :)

**Comment by CuteOne** [comment]
Well I would like to fix this for you too, im not happy unless its perfect :)

**Comment by kobasichoni** [comment]
hehehe maybe youll find a solution if you let it be for few days

**Comment by kobasichoni** [comment]
I would gladly donate 40 Euros If you could get a working WW MW profile,would be awesome

**Comment by kobasichoni** [comment]
but you said you dont heal :(

**Comment by CuteOne** [comment]
Let's try this....when you redid the files did also delete the config files in your WTF folder?

**Comment by kobasichoni** [comment]
I deleted everything WTF CASHE SETTINGS

**Comment by kobasichoni** [comment]
and badboy old one in addons folder

**Comment by CuteOne** [comment]
and yea I dont but other devs are working on healing profiles, its possible one of them may make a MW profile, if it goes too long I may just have to try to do it myself.

**Comment by kobasichoni** [comment]
I did not paste over it I replaced it with new

**Comment by kobasichoni** [comment]
well I dont care if its shamy or drood even I would like to have it....its easier to find grp as a healer these days

**Comment by CuteOne** [comment]
Ok delete everything again (only delete the BadBoy files in your WTF folder) and I will zip up my files and give you a link.

**Comment by kobasichoni** [comment]
ok i deleted it

**Comment by CuteOne** [comment]
[BadBoy.zip](https://github.com/BadBoy-Ultimate-Raider/BadBoy/files/546007/BadBoy.zip)

**Comment by CuteOne** [comment]
be sure you are out of the game completely when adding the wtf files

**Comment by kobasichoni** [comment]
ok lemme check

**Comment by kobasichoni** [comment]
its still there

**Comment by kobasichoni** [comment]
but I like where you moved everything

**Comment by kobasichoni** [comment]
:)

**Comment by CuteOne** [comment]
i have a custom UI...
![image](https://cloud.githubusercontent.com/assets/5498251/19622143/e4eaa42c-9870-11e6-8d93-d302f5029e73.png)

**Comment by kobasichoni** [comment]
so clean man... and youre not getting this issue?

**Comment by CuteOne** [comment]
Nope not a single problem

**Comment by kobasichoni** [comment]
maybe its a talent thats causing it,what talents did you chose?

**Comment by kobasichoni** [comment]
lemme try with those talents

**Comment by CuteOne** [comment]
![image](https://cloud.githubusercontent.com/assets/5498251/19622166/4cb77fc6-9871-11e6-8461-6fea0a44e3ba.png)

**Comment by kobasichoni** [comment]
same talents :(

**Comment by kobasichoni** [comment]
and youre using the Simc or AMR because AMR doesnt lose stacks at all but its lower in dps dunno why

**Comment by CuteOne** [comment]
SimC

**Comment by kobasichoni** [comment]
earth open yourself and take me....I dont know what to do to fix this..maybe its the elvui ima check to disable it

**Comment by CuteOne** [comment]
There should be no way for it to cast multiple blackout kicks in a row, each one has a check on it to not cast if it was the last one cast.

**Comment by kobasichoni** [comment]
its still doing it...casts a double one and then something between and again a double one or even tripple

**Comment by CuteOne** [comment]
My working hunch is something else is breaking the check on repeat casts

**Comment by CuteOne** [comment]
Ok replace this file in the BadBoy/Rotations/Monk/Windwalker folder and watch your chat...

[WindwalkerCuteOne.zip](https://github.com/BadBoy-Ultimate-Raider/BadBoy/files/546013/WindwalkerCuteOne.zip)

**Comment by kobasichoni** [comment]
Its arcane torrrent thats fucking me over

**Comment by kobasichoni** [comment]
Doesnt get used in between 2 kicks its on cd

**Comment by kobasichoni** [comment]
Yep disabled it and it works again

**Comment by kobasichoni** [comment]
the racial from belfs

**Comment by CuteOne** [comment]
so I am not familiar with Blood Elves, how does Arcane Torrent work?

**Comment by kobasichoni** [comment]
Arcane Torrent	Blood Elf Racial
Instant	1.5 min cooldown
Silence all enemies within 8 yards for 2 sec and restore 3% of your Mana.  Non-player victim spellcasting is also interrupted for 3 sec.

**Comment by kobasichoni** [comment]
it restores some energy aswell

**Comment by kobasichoni** [comment]
energy/focus/fury/mana/etcetera so its a dps gain to use it

**Comment by CuteOne** [comment]
i mean do you have to have a target to cast or can you cast it whenever?

**Comment by kobasichoni** [comment]
you dont need a target

**Comment by kobasichoni** [comment]
its an AOE silence

**Comment by CuteOne** [comment]
Are you able to see the spell id on it?

**Comment by kobasichoni** [comment]
i will try to see it ingame gimme sec

**Comment by kobasichoni** [comment]
Says its 129597

**Comment by CuteOne** [comment]
Ok just pushed an update, try that with racial on

**Comment by kobasichoni** [comment]
Works like a charm!!!!! Hasnt lost a single stack !

**Comment by CuteOne** [comment]
Perfect, sorry for the headache!

**Comment by kobasichoni** [comment]
np,donated 20 dollars :)

**Comment by CuteOne** [comment]
Thank you very much! That helps alot!

**Comment by kobasichoni** [comment]
I would gladly give another 20 for MW profile and im sure there is a lot of ppl who woulf aswel

**Comment by CuteOne** [comment]
If I knew healing I would be more apt to do it, again not to say I won't lol.
