### ISSUE TITLE
Doesnt attack

### ISSUE THREAD

**Issue by kobasichoni** [BadBoy-Ultimate-Raider/BadBoy#200]
Hey I was doing some questing and a dungeon today and saw that WW monk didnt want to attack Arcanator Prime the quest ellite mob and inside dungeon didnt want to attack That boss in neltharions lair when the boss goes in that stone and you have to find him. didnt want to attack the stone.

**Comment by leaderquebec** [comment]
work with me

**Comment by kobasichoni** [comment]
I dont know..few hours ago I finished HOV and it didnt want to attack the adds that 4 minibosses spawn before skovald the god king

**Comment by CuteOne** [comment]
Yea ive been trying to do some unit validation to prevent unintended attacks and while it works perfectly certain mobs (like the stone boss in Neltharion's Lair) it wont attack, this is likely due to the fact these units do not have a threat table. I have been thinking of how to validate these targets without breaking validation on normal targets.

**Comment by kobasichoni** [comment]
Yes I was about to say it,I disabled the smart targeting cc braking thingy and its fine. How far is the demo lock profile,did anyone send some feedback from dungeons/raids?

**Comment by CuteOne** [comment]
I havent yet, if you want to give it a shot id love feedback

**Comment by kobasichoni** [comment]
I will level my warlock to 110 in the next few days and will help you tweak the profile a bit. Rotation is quite simple.

**Comment by CuteOne** [comment]
Thanks

**Comment by kobasichoni** [comment]
Just wanted to ask if you found a solution for the problem with adds and that stone boss in Neltharions lair? I tried it yesterday on Odyn and it does attack his adds but not from the trash mobs before skovald. Would be nice to get a fix for it because when youre in mythic plus and all of a sudden you dont attack it is kinda weird :) oh and one more thing if its not much... I know you have the cds toggle macro option,but it would be much better to have a macro command for only cd on\cd off and not toggle. This way you can press it once and burst and after burst phase press it once more and it conserves cds if I epxlained it good...

**Comment by CuteOne** [comment]
Hum I dont recall having an issue with Odyn adds, and I did push a change in an attempt resolve the issue but have not ran Neltharion's lair as I have also been working on openers for the WW monk. It is possible that this work on the openers caused the freeze as they were still in flux in terms of functionality.

As for the toggle on/off (no auto) for cooldowns, I can surely whip something up but question for you would be if the toggle is currently on Auto would you want it to go to Off or On from there?

**Comment by kobasichoni** [comment]
Best would be if its just on and off but if its on auto it would be nice to go off. That way you can save cds for burnphase like on valkyr phase on odyn encounter. And the adds I was talking avout are the 4 kings before skovald the god king,they spawn an add that goes towards them and should be killed. They have no aggro from player they just move towards the boss

**Comment by CuteOne** [comment]
The edit I made to try to capture these targets that dont aggro was done yesterday, did your encounter include this update?

As for the toggle I can setup a burst key (assigned via keybindings) but I believe this option would need to be held (maybe I can make it a toggle)

**Comment by kobasichoni** [comment]
I ran a mythic plus hov yesterday around 1am thats exactly 20 hours ago if youre in the different time zone :) and it didnt attack them. Maybe I missed an update or something inbetween that time... a toggle would be awesome. That way i can leave cds off and toggle burst when I need it. Not bad

**Comment by CuteOne** [comment]
Ok last update has the burst toggle option...

![image](https://cloud.githubusercontent.com/assets/5498251/19742872/e6f4bc18-9b94-11e6-9522-6e6beae04808.png)

**Comment by kobasichoni** [comment]
Hey I have this weird issue i will write it here and then make a video again..its weird. I just updated the rotation and wanted to test it out on a dummy in class hall. It doesnt want to use any abilities but however if I click away it attacks...youll see on the video

**Comment by kobasichoni** [comment]
https://youtu.be/4L_AOBhCtNA

**Comment by CuteOne** [comment]
What Talents do you have and profile options set?

**Comment by kobasichoni** [comment]
It works again :) yeey! I swear man youre doing an awesome job with this one,I love it. I was doing some questing and was killing majestic elderhorn in highmountain,it was wooping its ass and all of a sudden a dk taunted it off me and profile stoped working. In my chat i had msg:
1:Tiger Palm
2:Touch of Death(uncastable)
3:Storm,earth and fire (uncastable)

**Comment by kobasichoni** [comment]
Now i saw it again and if i clicked away it worked again :) and then after whole series of white txt in chat it wrote opener complete. I will try to turn opener off and see what hapends

**Comment by CuteOne** [comment]
I think its still hanging on certain spells in the opening sequence, have I mentioned how much i hate openers yet lol, I will keep doing tests to try to uncover the cause.

**Comment by kobasichoni** [comment]
And you were talking about setting it not to attack kadgar well cant you see the unit id and just blacklist it?

**Comment by CuteOne** [comment]
It was more that I needed to set it to not attack friendly units
