### ISSUE TITLE
Demonology Rotation and stuff

### ISSUE THREAD

**Issue by kobasichoni** [BadBoy-Ultimate-Raider/BadBoy#204]
Hey I just wanted to share some info on the Demo rotation and stuff and I would like if you get the time to make it if not like this than atleast close to it it would be great :) so here are the Single target and Aoe rotations with videos what should be done and how. I would rather throw some cash at you making this work than spending money on some other rotations that suck anyway,because I believe you can do the job :)

Single Target: 
Here is a video of the following opening rotation: https://youtu.be/x0sJooNT41Y

[Prepull] Demonic Empowerment - 3 Soul Shards
[Prepull] Demonbolt - 4 Soul Shards
Doom & Felstorm
Demonbolt (praying for Demonic Calling proc) - 5 Soul Shards
Doomguard - 4 Soul Shards
Demonic Empowerment
Demonbolt (praying for Demonic Calling proc) - 5 Soul Shards
Hand of Gul'dan - 1 Soul Shards
Call Dreadstalkers - 1 Soul Shards - If no Demonic Calling proc, delay until next Hand of Gul'dan
Demonic Empowerment
Demonbolt (praying for Demonic Calling proc) - 2 Soul Shards
Demonbolt (praying for Demonic Calling proc) - 3 Soul Shards
Doom Tick - 4 Soul Shards
Hand of Gul'dan - 0 Soul Shards
Call Dreadstalkers - 0 Soul Shards - Cast here if no Demonic Calling proc earlier. If still no proc, cast Dreadstalkers before Hand of Gul'dan and settle for 2 less Imps.
Demonic Empowerment
Thal'kiel's Consumption
Resume priority rotation

General Rotation

Keep Doom up
Keep your Demons buffed with Demonic Empowerment
Call Dreadstalkers on cooldown
Cast Hand of Gul'dan when possible (4 Soul Shards)
Cast Thal'kiel's Consumption with at least 6 Wild Imps and 2 Dreadstalkers + Doomguard/Darkglare/GoServ: Felguard if possible
Fill with Demonbolt

General Thal'kiel's Consumption usage: 2 Dreadstalkers, 8 Wild Imps
It is best to combo your Demon summons in sets of 2 if you can. For example: Doomguard + Hand of Gul'dan, Hand of Gul'dan + Call Dreadstalkers or Doomguard + Call Dreadstalkers.

**# **The spec for Sustained/2+ Target AoE***\* will be: http://www.wowdb.com/talent-calculator#CfFm, the T15 talents can either be Demonic Calling or Shadowflame.

General Rotation

Keep Doom up
Keep your Demons buffed with Demonic Empowerment
Call Dreadstalkers on cooldown
Summon Darkglare on cooldown
Cast Hand of Gul'dan when possible (4 Soul Shards)
Cast Thal'kiel's Consumption with at least 6 Wild Imps and 2 Dreadstalkers + Doomguard/Darkglare
Fill with Shadow Bolt or Demonwrath if 3+ targets

You will want to use Thal'kiel's Consumption as often as you can with as many Demons as possible. I've opted out of putting in an opening rotation since it can vary quite abit depending on if you use Shadowflame or Demonic Calling, if it's instantly an AoE type fight or if it's delayed until after a more traditional opener could be used.
In a situation where there is the option of a more traditional to be used; follow the openers for Single Target and add in Darkglare in favour of 1 Wild Imp before you cast Thal'kiel's Consumption.
General Thal'kiel's Consumption usage: 2 Dreadstalkers, at least 6 Wild Imps
When Thal'kiel's Consumption Cooldown lines up with Darkglare and/or Doomguard, ensure they are up PLUS the normal Thal'kiel's Consumption usage Demons

as for Demonwrath when it should be used:
Demonwrath: 30% spell power per second per target, 0.15 shards per second per target
Shadow Bolt/Demonbolt is 40% spell power per second, 0.5 shards per second

40 / 30 = 1.33 targets for demonwrath to be more damage
0.5 / 0.15 = 3.33 targets for demonwrath to be more shards

**Comment by kobasichoni** [comment]
And one more thing, Darkglare should be summoned when there are lots of targets with doom because it only deals dmg to targets affected by doom spell

**Comment by CuteOne** [comment]
I can work with that, and money certainly helps with motivation...I am currently working on a commission for Guardian Druid, but I will be happy to get Demonology working better. :)

**Comment by kobasichoni** [comment]
Wow it would be great to have a good working tank spec atleast for mythic dungeons and drood is good :) as for lock I will try to give you feedback and help you make it fine :) affliction should be easy to code,every other bot had it done as one of first because it doesnt have a lot of crap to it

**Comment by kobasichoni** [comment]
Should be like feral of warlock specs :)

**Comment by dyser99** [comment]
Just wondering CuteOne, when you work on a commission for a profile, will it be released to the public or will it be private to the person paying you?

**Comment by CuteOne** [comment]
Depends on the person, but I would probably request more for private.

**Comment by dyser99** [comment]
How do we get in contact with you to get a profile commissioned? :)

**Comment by CuteOne** [comment]
Discord, Kynasha#8840
