### ISSUE TITLE
Broken :(

### ISSUE THREAD

**Issue by kobasichoni** [BadBoy-Ultimate-Raider/BadBoy#206]
Hey good morning :D
Since last update ench is broken and other specs are showing errors:

1x BadBoy\Rotations\Shaman\Enhancement\EnhancementCuteOne.lua:538: 'then' expected near ')'

Locals:

and demo spec shows:

56x [string "C:\Users\PC\Desktop\FH\Lua\Object.lua"]:66: The GUID does not belong to an existing object.
[C]: in function `ObjectGUID'
[string "C:\Users\PC\Desktop\FH\Lua\Object.lua"]:66: in function `ObjectID'
BadBoy\System\GeneralFunctions.lua:467: in function `canRun'
BadBoy\Rotations\cCharacter.lua:153: in function `baseUpdate'
BadBoy\Rotations\Warlock\cWarlock.lua:90: in function `classUpdate'
...\BadBoy\Rotations\Warlock\Demonology\cDemonology.lua:85: in function `update'
...s\BadBoy\Rotations\Warlock\Demonology\Demonology.lua:12: in function `WarlockDemonology'
BadBoy\System\Core.lua:352: in function <BadBoy\System\Core.lua:247>

Locals:
(*temporary) = "target"

Ive seen you made few changes to warlock routine,its working proppah :) now I have a reason to max level it and help you tweak it

**Comment by kobasichoni** [comment]
btw when I say ench is broken i mean it doesnt load at all

**Comment by kobasichoni** [comment]
Demonology has the lua error when you mount up

**Comment by CuteOne** [comment]
Yea I really shouldn't do Late Late Nightly updates, enhancement should already be fixed and the ObjectID one will probably have to be rolled back/undone.
