### ISSUE TITLE
Demonology Warlock

### ISSUE THREAD

**Issue by SvsGit** [BadBoy-Ultimate-Raider/BadBoy#207]
Message: ...terface\AddOns\BadBoy\Rotations\Warlock\cWarlock.lua:73: attempt to call global 'cFileBuild' (a nil value)
Time: 11/06/16 15:10:11
Count: 1206
Stack: [C]: in function `cFileBuild'
...terface\AddOns\BadBoy\Rotations\Warlock\cWarlock.lua:73: in function `classUpdate'
...\BadBoy\Rotations\Warlock\Demonology\cDemonology.lua:84: in function `update'
...s\BadBoy\Rotations\Warlock\Demonology\Demonology.lua:12: in function `WarlockDemonology'
Interface\AddOns\BadBoy\System\Core.lua:352: in function <Interface\AddOns\BadBoy\System\Core.lua:247

**Comment by CuteOne** [comment]
That should not be possible as it very much exists...wonder if it was a loading issue.

**Comment by kobasichoni** [comment]
It is a loading issue i just reload addons and its fine
