### ISSUE TITLE
Cannot run any rotation for the pala except retribution

### ISSUE THREAD

**Issue by Norokir** [BadBoy-Ultimate-Raider/BadBoy#208]
Hello Team,
I cannot make Badboy run for the holy and prot specs for my paladin. It runs pretty well for retribution. 
Config window does not appear for holy and prot, appears only for retri.
What could be a reason?

![wowscrn](https://cloud.githubusercontent.com/assets/23387480/20192361/9300bad2-a79a-11e6-935f-f76b991c0ac4.jpg)

**Comment by CuteOne** [comment]
Ret is the only developed profile at this time.

**Comment by Norokir** [comment]
Oh, ok :)
Any info on how soon heal profile will be ready?

**Comment by CuteOne** [comment]
I do not sadly, healing profiles are kinda my kryptonite. That said I will
be attempting a Resto Druid profile soon and if that goes well you can plan
on others being done as well.
