### ISSUE TITLE
assassination rogue does not use cooldowns

### ISSUE THREAD

**Issue by gomisensei** [BadBoy-Ultimate-Raider/BadBoy#62]
Vendetta is probably just tied to Shadow Reflection, which shows up in the main button, but does not activate, at least, not on target dummies, regardless of state of cooldowns button.

**Comment by CuteOne** [comment]
This should be fixed, not sure about Shadow Reflection as im still only 81.

**Comment by gomisensei** [comment]
nope, same thing, shows the shadow reflection texture in the bar, but doesn't actually cast the spell.  Also, typo in line 313 of rotations\rogue\assassination.lua, venRemain should probably be vanRemain, throws up a lua error in combat

**Comment by ragnarger** [comment]
is this fixed?

**Comment by CuteOne** [comment]
This issue is still on-going as I am still working on Leveling my rogue (level 87 currently), I appologize for the delay as I have limited time to play with my new job.
