### ISSUE TITLE
Memory Leakage?

### ISSUE THREAD

**Issue by GabbzGit** [BadBoy-Ultimate-Raider/BadBoy#80]
I have issues and sometime my wow crashes. 

Looking at memory usage Bad Boy starts low at 1 MB but after a while its climbing around 16 MB.
Please comment your badboy memory usage so if necessary we can track and discover if there is a issue.

**Comment by cassrgs** [comment]
well if fh injection make addons leak maybe its not even bb that make game crash sporadically even after reload ui

**Comment by ragnarger** [comment]
We should Collect Infos about Running Addons on users with crashes. All Info is useful. 
Running rota, addons,...

**Comment by cassrgs** [comment]
the moment the game crash everythjing frozes. Is there a way or another addon to track and register memory activity on a file so we could check it after crash?
