### ISSUE TITLE
SotF

### ISSUE THREAD

**Issue by cukiemunster** [BadBoy-Ultimate-Raider/BadBoy#90]
Resto druid is not using SotF correctly regardless of what you put as values. For example if you set it to use at 100 health, with 1 person, it still never uses Swiftmend~~~>WG, it just seems to continue along with the rotation as normal.

**Comment by cukiemunster** [comment]
Still an issue =[

**Comment by cukiemunster** [comment]
With all the devs working on resto druid, can we PLEASE get someone to look into this?

**Comment by Defmaster** [comment]
Nobody has updated the Resto profile for a while. I looked into the code and it seems "Soul of the Forest" is not implemented yet.
