### ISSUE TITLE
[Priest]Nagrand talbuk outpost

### ISSUE THREAD

**Issue by Neretil** [BadBoy-Ultimate-Raider/BadBoy#91]
The priest profile doesn't work with the talbuk mount (outpost) in Nagrand, it cast nothing.

**Comment by ragnarger** [comment]
i do not have this outpost to test it. but i will look for a fix

**Comment by ragnarger** [comment]
try to use it again and report to me.
should be fixed

**Comment by Neretil** [comment]
It's working!
Thanks for the quick fix
