### ISSUE TITLE
Liquid Magma - Enhancement Shaman

### ISSUE THREAD

**Issue by derfred666** [BadBoy-Ultimate-Raider/BadBoy#92]
I was trying out the enhancement profile and noticed that it doesnt use the talent liquid magma, any plans on supporting that? Alternatively I could use a pause rotation click talent macro, but I dont really know how to set it up.

Thanks for an otherwise great profile!

**Comment by malloot** [comment]
For a temp fix you could copy a pause rotation part out of the ret pally file. Line 14 has a pause on left alt. You can than keybind the ability on alt+something and you have your manual cast option

**Comment by CodeMyGit** [comment]
Cpoworks is updating enhancement these days, I'll let him know but im not sure his shaman is 100 yet.

**Comment by CodeMyGit** [comment]
He did push some fixes, is your issue resolved? :)
