### ISSUE TITLE
[Warrior][Fury]Profile options menu

### ISSUE THREAD

**Issue by Neretil** [BadBoy-Ultimate-Raider/BadBoy#93]
Right click on the fire icon to bring up the profile options window is bugged while using the Fury profile (works fine with Arms). It gives a "Badboy Start/Stop is Stopped in General options... etc" error message only.

Yes, Start/Stop is enabled and the bot works perfectly with the togle frame. Its only the options menu

**Comment by CodeMyGit** [comment]
Make sure you see the main button(the one with range) and that its highlighted, and in options that Start/Stop is checked.

By the way Avery is gonna rewrite fury from scratch, should be good in a couple days!

Thanks for feedback!
