### ISSUE TITLE
wow crash (feral only...)

### ISSUE THREAD

**Issue by gomisensei** [BadBoy-Ultimate-Raider/BadBoy#94]
seems to happen only on feral, in combat, randomly

**Comment by gomisensei** [comment]
![image](https://cloud.githubusercontent.com/assets/2192653/5602715/c2c4c88a-9315-11e4-8cf9-9b12aa5dd326.png)
(better image)

**Comment by Kiwical** [comment]
Yeah i get that but its random i can play for hours without getting the error while in combat but when it does crash it's always when i am in combat, happened to the Rogue profile as well but it was different,wow hanged no crash error.

**Comment by cassrgs** [comment]
Maybe this could be related with memory leak already issued. check on performance icon if badboy is using big ammounts of memory. If so try a /reload ui. Another thing to try its load firehack on character selection screen, not after. See if by making this the number of cracs ceases or decreases.

**Comment by Neretil** [comment]
Not memory leak. It just happens. I just started to level my monk and with that profile WoW crush like every 15 mins, so it's not feral only

**Comment by CuteOne** [comment]
I wonder if this is due to UnitExists, like CML figured it might be....ill keep investigating.

**Comment by ragnarger** [comment]
cassrgs said:
check on performance icon if badboy is using big ammounts of memory
pls reply to this!

**Comment by Kiwical** [comment]
Didnt notice any memory issues with badboy, elvui uses more memory than badboy did

**Comment by gomisensei** [comment]
well, it hasn't ever happened on the WW badboy profile, that I can recall...

**Comment by CodeMyGit** [comment]
UnitExists are already out of the bot since https://github.com/BadBoy-Ultimate-Raider/BadBoy/commit/cd252869c78b2239e34b4a4e078346c3bc2e719c

**Comment by CodeMyGit** [comment]
Seems like there were still some at profile levels, ill add one more check to dynamicTargetting to make sure, thanks for feedback guyz

**Comment by Kiwical** [comment]
This is what i get when i play the rogue profile im only lvl 73 it crashed on last boss in an instance

 Problem Event Name:	APPCRASH
  Application Name:	Wow-64.exe
  Application Version:	6.0.3.19342
  Application Timestamp:	548f8bcd
  Fault Module Name:	FireHack.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	546e99cb
  Exception Code:	c0000005
  Exception Offset:	0000000000020662
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	5129
  Additional Information 1:	3d0f
  Additional Information 2:	3d0fc34a3ba910d21f1613a8565be7bb
  Additional Information 3:	9a7a
  Additional Information 4:	9a7a079fbd8f0ce855a20014541074f1

**Comment by CodeMyGit** [comment]
Could you specify wich rogue profile please? :)

**Comment by Kiwical** [comment]
Assassination rogue profile

**Comment by CodeMyGit** [comment]
134 should be gone since yesterday.. thanks for reporting. if you guyz having issues with FH/BB crashing your client please refer to our Readme atop GitHub for informations on what can be done.

**Comment by CuteOne** [comment]
I am closing this issue for now, as the corrections to 134 error are on going. As for assassination I plan to look into this rotation when I have time (best guess will be this weekend).
