### ISSUE TITLE
getNumEnemies broken

### ISSUE THREAD

**Issue by popster** [BadBoy-Ultimate-Raider/BadBoy#95]
Latest update broke getNumEnemies

/dump getNumEnemies("player",30)
returns 0 regardless

**Comment by ragnarger** [comment]
use 
#getEnemies(unit,distance)
e.g.: 
#getEnemies("player",30)

**Comment by popster** [comment]
Thanks!

**Comment by popster** [comment]
I can't/don't know how to compare numbers with tables though :(

**Comment by popster** [comment]
Thanks!

**Comment by CodeMyGit** [comment]
oh god i forgot that one ill make it use the new design

**Comment by CodeMyGit** [comment]
solved and pushed thanks for feedback!
