### ISSUE TITLE
boomy aoe broken

### ISSUE THREAD

**Issue by cassrgs** [BadBoy-Ultimate-Raider/BadBoy#96]
hello there, on the last booooomy overhaul aoe seems broken, its no using starfall and keep castins starfire and wrath as single

**Comment by CodeMyGit** [comment]
lol, for me it aggro/dot the whole map with moonfires and starfall, anyone experiencing same? what level are you? :)

**Comment by cassrgs** [comment]
lv 100. tried only once near exarch refugee on the everspawning fel mobs to grind follower rep. Gona try again on another environment to see how it goes

**Comment by CodeMyGit** [comment]
boomy kick asses let me know if theres anything :)
