### ISSUE TITLE
Arms Profile

### ISSUE THREAD

**Issue by Kiwical** [BadBoy-Ultimate-Raider/BadBoy#97]
Does this work at low levels  im leveling one i get this error shows so many errors i have to turn Lua errors off

Message: Interface\AddOns\BadBoy\System\Core.lua:191: attempt to call global 'ArmsWarrior' (a nil value)
Time: 01/08/15 14:53:36
Count: 2687
Stack: [C]: in function `ArmsWarrior'
Interface\AddOns\BadBoy\System\Core.lua:191: in function <Interface\AddOns\BadBoy\System\Core.lua:165>

**Comment by chumiiger** [comment]
This was due to an error in .toc, already fixed

But.. Arms is still not 100 ready, I will work on it during next week I think

**Comment by Kiwical** [comment]
Yeah im leveling a warrior he is only like 17 i was just wondering if it was working enough at low levels
