### ISSUE TITLE
Combat Rogue

### ISSUE THREAD

**Issue by Kiwical** [BadBoy-Ultimate-Raider/BadBoy#98]
Casts deadly poison over and over doesnt use rotation at all

**Comment by CodeMyGit** [comment]
I think Tocsin isnt around but Cuteone will surely take care of it, thanks for reporting!

**Comment by Kiwical** [comment]
Do you know if a sub profile will be made, Sub and combat are the best specs at the moment

**Comment by CuteOne** [comment]
I've been debating it
