### ISSUE TITLE
Improve castGround? (suggestion)

### ISSUE THREAD

**Issue by popster** [BadBoy-Ultimate-Raider/BadBoy#99]
Any chance of getting more conditions into castGround? Right now it casts in dead center of the target when it would be AoE dps increase if it was able to position itself to cast so it would hit all current enemies within spell range, kind of like castHealGround has for players.

**Comment by masoudshafiee** [comment]
I think u can combine castGround  with  #getEnemies to find best target for aoe like
local thisUnit = enemiesTable[i]
local enemiesAround = #getEnemies(thisUnit.unit,8) 
if enemiesAround >= 2
then
if castGround(thisUnit.unit,spellid,range) then  return end
 end	
en

**Comment by popster** [comment]
Yup that does work, thanks a bunch!
